### ISSUE TITLE
Three questions

### ISSUE THREAD

**Issue by privHypp** [vshymanskyy/StandWithUkraine#105]
Three questions:

1. Why, if "Russia shelled the Donbass for 8 years" the troops of the LDNR are fighting shoulder to shoulder with the Russian army and liberating the territories of the republics, and the Donetsk and Luhansk residents support them?

2. If "the Russian army shoots civilians" in the same Bucha, why the Russian armed forces issue humanitarian aid in Kherson, Melitopol and other liberated cities? Why? then shoot them?

3. Your house is destroyed. Were there Ukrainian troops in your city at the time of the attack, such as in Mariupol?
If so, then ask them a question: why did they do this, why did they decide to cover their positions with civilians, your home?

And, just the attitude towards captured soldiers
Ukrainian  vs Russian.. [redacted] What is closer to you?

**Comment by benjamingr** [comment]
I feel so bad there are people facing _this much misinformation_ around the world ☝️

**Comment by vshymanskyy** [comment]
I'm not sure why are these questions posted here. Use google.
Except question 3. Which I can definitely answer that it was done by Russians. Ukraine didn't have control over the city at that time.
I don't want to further explain anything here.

**Comment by vshymanskyy** [comment]
Also, I revoved the attached videos, as they are manipulative.

**Comment by vadimdemedes** [comment]
Guys, I'd suggest to not waste your time with issues like that. Lock, close and move on.
