### ISSUE TITLE
In fact, this repository is a pool of anger.

### ISSUE THREAD

**Issue by bluemiaomiao** [vshymanskyy/StandWithUkraine#108]
My comments are locked and deleted, which is really dictatorial:

- Repository owner deleted a comment from [bluemiaomiao](https://github.com/bluemiaomiao) [2 minutes ago](https://github.com/vshymanskyy/StandWithUkraine/issues/97#event-6399208241)
- Repository owner locked and limited conversation to collaborators [2 minutes ago](https://github.com/vshymanskyy/StandWithUkraine/issues/97#event-6399209204)
- Repository owner deleted a comment from [bluemiaomiao](https://github.com/bluemiaomiao) [2 minutes ago](https://github.com/vshymanskyy/StandWithUkraine/issues/97#event-6399209846)
- Repository owner deleted a comment from [bluemiaomiao](https://github.com/bluemiaomiao) [2 minutes ago](https://github.com/vshymanskyy/StandWithUkraine/issues/97#event-6399210349)

Let me state the facts again: in the recent news, the Ukrainian army bombed the railway station in Ukraine, and the Ukrainian civilians were called human shields of the Ukrainian government. And the U.S. and NATO used the politically mindless Ukrainian government to sanction Russia. The next victims were Ukrainian civilians. Let's think, why can't Zelenski join NATO?

**Outsiders see, the Ukrainian government is really a big joke these days.**

**Comment by veelenga** [comment]
4 of your GitHub comments have been removed and you are literally *screaming*. Such a tragedy, yeah. 

What would you do if foreigners (russian soldiers) come to your house, kill your neighbors, torture your family, rape women? Nah, that's just a big joke...

**Comment by bluemiaomiao** [comment]
Why do you think the Ukrainian government and the Ukrainian people should stand together?

**Comment by fabswt** [comment]
So many people drank the Kool-Aid. Where were they when people were getting bombed for 8 years in the East of Ukraine? People joining the slogan *du jour* without looking at history (or facts, but they're hard to get) is brainless, and they're being used politically.

I don't welcome slogans in the open-source projects I use. It's one more form of propaganda.  

I'm wary of people claiming to have all the facts. And so should be smart people (and there's a ton of them in tech.)

**Comment by cristaloleg** [comment]
@bluemiaomiao https://en.wikipedia.org/wiki/Internet_Research_Agency & co.

Leaving misinformation and false signals (read propaganda) is letting them win info war, that's not acceptable. Removal of such comments it's just a correct action.

**Comment by LukaDong77** [comment]
> 4 of your GitHub comments have been removed and you are literally _screaming_. Such a tragedy, yeah.
> 
> What would you do if foreigners (russian soldiers) come to your house, kill your neighbors, torture your family, rape women? Nah, that's just a big joke they say…
Have you asked this question for the Iraqis? Have you asked for the Palestinians? Have you asked for Afghans? Ridiculous. In addition, I also want to ask you what you think of the fight against Nazis during World War II?

**Comment by LukaDong77** [comment]
> @bluemiaomiao https://en.wikipedia.org/wiki/Internet_Research_Agency & co.
> 
> Leaving misinformation and false signals (read propaganda) is letting them win info war, that's not acceptable. Removal of such comments it's just a correct action.


Who gives you confidence that others are wrong? According to my personal experience, the western media are full of countless ridiculous lies. Delete other people's speech and keep your own speech. This is what you call freedom of speech?

**Comment by vshymanskyy** [comment]
@bluemiaomiao moreover your account will be blocked if you continue spreading misinformation and shifting facts.

**Comment by vshymanskyy** [comment]
@LukaDong77 account was created 27 days ago. Only to comment on such tickets, I suppose.

**Comment by vadimdemedes** [comment]
@vshymanskyy Why not just block him now? He's done it multiple times already.

**Comment by LukaDong77** [comment]
See, that's all you can say. Talk about freedom of speech, but you block the accounts that don't accord with your opinions. One account has been blocked and tens of thousands of accounts have been reborn. Block it. Anyway, my blocked account is no worse than this one. You will eventually be bitten by your own double standards. Let's see. My purpose is to let more people know your hypocrisy. The best way should be to make a platform for yourself. Only those who flatter you can comment, and those who don't flatter you are forbidden to comment. Do you still believe in freedom of speech?

**Comment by vshymanskyy** [comment]
Go find freedom of speech in Russia.

**Comment by vshymanskyy** [comment]
Back to the topic.
We, Ukrainians, are angry as hell. Indeed.
We will do everything so that Russia pays for all the terrible things it did. The price will be high.
Ukraine already payed an enormous price for its liberty, dignity and democracy. And we will do even more.
