### ISSUE TITLE
"reputable news" link 404s

### ISSUE THREAD

**Issue by stephenmathieson** [vshymanskyy/StandWithUkraine#112]
The linked underlined by this image:

![screenshot of standwithukraine website](https://user-images.githubusercontent.com/571265/163039916-3379b6a4-5a89-4d31-8a51-55abfc8886f1.png)

Leads to https://standwithukraine.pp.ua/WarNews.html, which 404s.

**Comment by stephenmathieson** [comment]
The link works when there hyphens in the URL ("stand-with-ukraine").

**Comment by vshymanskyy** [comment]
I don't see this bug when i navigate to https://stand-with-ukraine.pp.ua/ and click this link.
It also works from https://github.com/vshymanskyy/StandWithUkraine/tree/main/docs#readme

I don't think there's any real issue here

**Comment by jdreesen** [comment]
I don't get a 404, I just get a different website.

![grafik](https://user-images.githubusercontent.com/424602/163214407-805052bf-903c-431e-982e-369df35aa2ee.png)

vs

![grafik](https://user-images.githubusercontent.com/424602/163214511-ae4e0f5f-641e-4527-b26d-7e98178653e8.png)

**Comment by vshymanskyy** [comment]
i don't know why they did it...

**Comment by stephenmathieson** [comment]
I don't know either, but they did. I assume others have too.

IMO redirecting `standwithukraine.pp.ua` to `stand-with-ukraine.pp.ua` is probably the best/simplest solution.

**Comment by vshymanskyy** [comment]
i'm not afilliated with http://standwithukraine.pp.ua/

**Comment by stephenmathieson** [comment]
Oh weird. Looks like some sort of phishing scam. Yesterday, it was a copy of https://standwithukraine.pp.ua.

**Comment by vshymanskyy** [comment]
https://standwithukraine.pp.ua/ is a legit (but outdated) website of "Come Back Alive" Non-Government Charity Organization.
Which is a verified organization, and is present on our list as well :+1:

**Comment by webknjaz** [comment]
> https://standwithukraine.pp.ua/ is a legit (but outdated) website of "Come Back Alive" Non-Government Charity Organization.
> Which is a verified organization, and is present on our list as well :+1: 
> 

Interesting... When I was registering https://stand-with-ukraine.pp.ua, https://standwithukraine.pp.ua was not a thing and I was considering to register it myself as an alias. But decided that I probably don't need it. Maybe somebody from the charity decided to get it, after all.

**Comment by vshymanskyy** [comment]
After some verification, we consider `standwithukraine.pp.ua` as **possible a phishing attempt**.
ComeBackAlive org refused any relation to this website.
However, it looks like it was just used once in the VIM wiki. Currently, it's not mentioned anywhere else: [seash results](https://github.com/vshymanskyy/StandWithUkraine/search?q=standwithukraine.pp.ua)
