### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by lerbro** [vshymanskyy/StandWithUkraine#113]
That sounds ridiculous. The older generation in your country fought against NATO. They are heroes; And you are now joining NATO - the enemy of your country's older generation. NATO wants to destroy your faith all the time. Now it seems that they have succeeded.

**Comment by FoggyFinder** [comment]
You clearly know nothing about the subject.

**Comment by lerbro** [comment]
> You clearly know nothing about the subject.


You know nothing about the main cause of the Ukrainian problem.

**Comment by cristaloleg** [comment]
Yet again 6hr old account reveals the "truth". C'mon.
