### ISSUE TITLE
How about this

### ISSUE THREAD

**Issue by kgnfth** [vshymanskyy/StandWithUkraine#116]
People with 'blue eyes and blonde hair' dropping bombs over the Middle East and Africa is OK. ?

**Comment by jdreesen** [comment]
[What about...?](https://en.wikipedia.org/wiki/Whataboutism)

**Comment by FoggyFinder** [comment]
> People with 'blue eyes and blonde hair' dropping bombs over the Middle East and Africa is OK. ?

Usually, I ignore this nonsense but since you're from Chulak I'll ask to clarify how did you get to this conclusion ? 

What force you to think that are any connections between ruscist's invasion and whatever you're referring to ?

**Comment by webknjaz** [comment]
Closing this as it seems like a spammer just wanted to do the same the r*ssian nazi propaganda (and their troll bots) do. Not a real question, they clearly just wanted to insult us.
