### ISSUE TITLE
 Please fix the #StandsWithUkraine link (Issue #24)???

### ISSUE THREAD

**Issue by ldijkman** [vshymanskyy/StandWithUkraine#117]
Please fix the #StandsWithUkraine link (Issue #24)

**************************
got this email => subject link to issue 24 is that relevant??
*******************************************************

Volodymyr Shymanskyy <notifications@github.com> Afmelden
11:35 (6 uur geleden)
aan ldijkman/randomnerd_esp32_wifi_manager, Subscribed

[standwithukraine.pp.ua](http://standwithukraine.pp.ua/) is probably a phishing website. Please link to https://stand-with-ukraine.pp.ua/

*****************************************************
i copied pasted the banner  code from 
https://github.com/Bodmer/TFT_eSPI/wiki
************************************************

![img_1_1649085291012](https://user-images.githubusercontent.com/45427770/163595916-73e401fe-66c8-4f67-9a8c-d2c2ccbbc613.jpg)

**Comment by webknjaz** [comment]
It's been fixed in that wiki AFAICS

**Comment by jdreesen** [comment]
Yes, seems like the account that added it there doesn't exist anymore. Probably it was created just for adding the phishing link. So I changed it to be the real one ;)
