### ISSUE TITLE
schizo

### ISSUE THREAD

**Issue by 3jq** [vshymanskyy/StandWithUkraine#119]
dude you are actually SO SCHIZO
please take your meds

i am against the current situtation between ukraine and russia BUT dude you are so schizo
too much propaganda on the place that shouldn't have it

**Comment by 3jq** [comment]
if you close this issue and lock the conversation to me you are schizo x2
same stuff if u delete this comment

**Comment by webknjaz** [comment]
Sigh... This exactly demonstrates how abusive russian nazis are. Closing this spam harassment attempt.
Go behave like this at home. This is a civilized place where you are not welcome.
Feel free to follow the warship. You know the way.
