### ISSUE TITLE
Additional banner

### ISSUE THREAD

**Issue by dmitry-sinina** [vshymanskyy/StandWithUkraine#120]
Could you add additional banner for projects(opensource on github) where whole team are Ukrainians. Currently we are using "This project was created by a developer from Ukraine.." , but  it looks like we have one developer.

**Comment by vshymanskyy** [comment]
How about this? 
https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/banner-direct.svg

**Comment by dmitry-sinina** [comment]
In our case whole development team are Ukrainians so "substantial contribution" doesn't fit perfectly as for me.
