### ISSUE TITLE
peace

### ISSUE THREAD

**Issue by lerbro** [vshymanskyy/StandWithUkraine#123]
Staying away from NATO is the best way to keep peace with the Ukrainians. What is Ukraine joining NATO for? To bomb the Federal Republic of Yugoslavia? To bomb Iraq?

**Comment by cristaloleg** [comment]
Ukraine do **not** join NATO, quick Googling: https://www.theguardian.com/world/2022/mar/15/kyiv-facing-dangerous-moment-amid-signs-of-russias-tightening-grip

**Comment by lerbro** [comment]
I know that. Have this tendency. ![https://twitter.com/NATOinUkraine](https://twitter.com/NATOinUkraine)

**Comment by cristaloleg** [comment]
👌 https://en.wikipedia.org/wiki/Member_states_of_NATO

**Comment by shayneoneill** [comment]
Ukraine has not joined Nato. In fact NATO rejected Ukraines membership AND Zelensky has stated his government is willing to completely rule it out in exchange for Russia ending its massacre.

**Comment by webknjaz** [comment]
> Joined 7 days ago

This is a nazi spam bot account, nothing to discuss with it.

r*ssian :ship: you know the direction.
