### ISSUE TITLE
Information correctness on the banner

### ISSUE THREAD

**Issue by sanblch** [vshymanskyy/StandWithUkraine#125]
I do imagine you are angry and struggle the war. But I need to mention that information on the banner seems to be incorrect. Russian troops torture and rape people. It is a lie. Please provide facts or fix the text. War will end, but reputation never whiten again.

**Comment by webknjaz** [comment]
> It is a lie.

I wish. But we don't get our information from propagandist sources. We get it from people who actually witnessed this. Some of us got it by looking out of our windows. You're either ignorant or a propagandist. Although, I don't care enough to figure out which one. You're behaving maliciously and this is not welcome here, feel free to do this at home, together with the rest of your compatriots.

Please, don't lie here ever again. It's a civilized place, not r*ssia.

> reputation never whiten again.

You just lost your reputation. You know where to go r*ssian nazi :ship:
