### ISSUE TITLE
Nginx is part of F5, an american technology company

### ISSUE THREAD

**Issue by azjezz** [vshymanskyy/StandWithUkraine#13]
The document stats to boycott Nginx, however, Nginx is owned by F5 ( https://www.f5.com/ ), a Non-Russian company. 

see: https://www.nginx.com/blog/nginx-is-now-officially-part-of-f5/

**Comment by vshymanskyy** [comment]
Nginx has office in Moscow:
https://www.zdnet.com/article/russian-police-raid-nginx-moscow-office/
So, they continue paying taxes in Russia. Is there any official announcement addressing that?

**Comment by azjezz** [comment]
Microsoft ( which owns GitHub ) has an office in Russia, so does Facebook, and Google.

**Comment by vshymanskyy** [comment]
Probably need to get them onto the list then.

**Comment by vshymanskyy** [comment]
@azjezz it here at least an official position of Nginx, where it's clear that they are against the war?
