### ISSUE TITLE
WinRAR shouldn't be on the boycott list. 7-Zip should.

### ISSUE THREAD

**Issue by nobri** [vshymanskyy/StandWithUkraine#135]
WinRAR is currently on the list of companies/programs you should boycott.
However, it doesn't make much sense to me as it is a German company based in Berlin.
7-Zip however is developed by a Russian developer and should therefor be on the list, not WinRAR.

**Comment by decorator-factory** [comment]
Are you suggesting to boycott a free an open-source project? Let's also boycott `nginx` then

**Comment by nobri** [comment]
> open source should NOT be thought belonging to any region

Makes sense but one of the first things being said in the README is to:
> Get rid of Russian software and dependencies

So what do you consider Russian software? A software that's in the Russian language or a software developed by a Russian?
Where do you draw the line? When is it considered Russian?

Anyhow. Even if you disagree it doesn't change the fact that WinRAR itself has nothing to do with Russia.
I think it would only be fair to not include it on the list just because the OG dev is a Russian.
It is the same reason you are arguing that 7zip should not be included.

**Comment by lwd-temp** [comment]
Actually, I agree that WinRAR shouldn't be on the list. It's source code is controlled by a German company, so it probably won't do harm to any person.

7-Zip's source code and (or) binary is included by many open source projects. And Russian developers also participate in many projects. We can't boycott them all, which means "Russian developer" is not a proper reason.

**Comment by nobri** [comment]
> We can't boycott them all, which means "Russian developer" is not a proper reason.

100%. I think it's stupid to boycot anything Russian just because it's Russian. Not every Russian supports what's currently going on. We can't put them all into the same drawer.

**Comment by gusbemacbe** [comment]
Let us call @vshymanskyy and ping @ghaiklor (he is better to know because he is one of main responsible for the «Stand with Ukraine» repository) and @lyubomyr-shaydariv. Let's see what their decision.

**Comment by nobri** [comment]
To clarify, I do not support the war in any way or form. But neither do I support the thought of just boycotting everything that is made by a Russian, because not every Russian supports the war. As I have stated above:

> We can't put them all into the same drawer

However, the reason I opened this issue is because if you really just want to boycott everything that was **made** by a Russian individual, then include 7-Zip in your list because it was in fact made by a Russian. Don't contradict yourself.

Quote from the README:
> Get rid of Russian software and dependencies

I personally think that it is a utterly stupid approach but I am not the one to judge. 🤷🏻

_And lastly: WinRAR still has nothing to do with this. 😂_

**Comment by gusbemacbe** [comment]
While the owner and the collaborators still don't answer, you can calmly PeaZip as a safe alternative. PeaZip's developer Giorgio Tani is from Italy. It's available on all platforms.

**Comment by lyubomyr-shaydariv** [comment]
I'm kind of (not) surprised that the title of the issue says both "WinRAR shouldn't be on the boycott list." **and** "7-Zip should.". The latter is open-source and free, whilst the former is a commercial product (correct me if I'm wrong for these two). I have no idea how much affiliated WinRAR are the Roshals are nowadays, but if this product is still used to sponsor terrorussia in whatever way, then it's in the right place. The OP sounds pretty much in terrorussian noisy narratives fashion too: noise, responsibility transfer right in the title of the issue, missing the explanation how software or services can get excluded from the list, saying "utterly stupid" etc. Please read these last two lines from the very below of the [list](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/Boycott.md):

- [L180:](https://github.com/vshymanskyy/StandWithUkraine/blob/a4681b10a0c27886befae72770132e608346787e/docs/Boycott.md?plain=1#L180) The list is still being verified. There may be false positives, please create issues to fix them
- [L181:](https://github.com/vshymanskyy/StandWithUkraine/blob/a4681b10a0c27886befae72770132e608346787e/docs/Boycott.md?plain=1#L181) Companies will be moved to allow list if there's compelling evidence of them suspending operations in Russia

The last phrase (for whatever reason by whoever put WinRAR into it) implies that WinRAR makes business in terrorussia. Merely make an evidence it does not. That's it.

(P.S. WinRAR sucks.)

**Comment by nobri** [comment]
> I'm kind of (not) surprised that the title of the issue says both "WinRAR shouldn't be on the boycott list." and "7-Zip should."

1. Either put "everything Russian" on your list or don't, but don't play favorites. (Nr. 7)
That's the only reason why I named the issue this. Maybe I should have been clearer, sorry for that.

> The latter is open-source and free, whilst the former is a commercial product (correct me if I'm wrong for these two).

2. That's correct. But please update the description if OSS should not be included on the list.
As I said above, I think you should either include everything that's Russian (absolutely stupid approach in my opinion) or don't. But please make a decision and don't play favorites, you're sending the wrong signals here.

> if this product is still used to sponsor terrorussia in whatever way, then it's in the right place.

3. This is ridiculous. You make it sound like all of WinRAR's revenue is being used to sponsor a war.
Where is the evidence? As a German company they pay German taxes. I'm shocked but I have honestly kind of expected this.,,

> The OP sounds pretty much in terrorussian noisy narratives fashion too: noise

4. That's honestly concerns me and you clearly haven't read what I said above.
I explicitly said that I *don't* support the war but that answer was to be expected as this is a pretty heated topic.
When maintaining a "political" repo like this you should keep a clear mind/head and look at things from a neutral perspective.
Do not make up assumptions and stop accusing people in that regard.

> Responsibility transfer right in the title of the issue, missing the explanation how software or services can get excluded from the list, saying "utterly stupid" etc.

5. I don't see a problem with either the title of the issue nor my explanation. I gave all the information someone should need to be able to base their decisions off of it or at least figure out what's going on/it is about, it's straight to the point. Instead of just criticizing me you could have provided some feedback, all you're doing it literally what you criticized me for, transfer of responsibility.

> The last phrase (for whatever reason by whoever put WinRAR into it) implies that WinRAR makes business in terrorussia. Merely make an evidence it does not. That's it.

6. While I understand that you want to to have some evidence, you also clearly seem to have no evidence that WinRAR does actively sponsor the war. If so, feel free to drop me a link. Don't expect others to deliver evidence when you make bald claims like that but don't deliver evidence yourself.

> (P.S. WinRAR sucks.)

7. This is just clear fanboy-ism over a different product. As I said in Nr. 1, "don't play favorites".
Especially not when maintaining a repository like this.

And yes, I do think this is "utterly stupid". You just put everything with a remote connection to Russia in one massive drawer. Are you going to ban every company that has/has had Russian employees? Would my company be banned because we have a Russian employee on our team? What kind of approach is this? While I do understand your frustrations you have to realize that not every human is the same and there are Russians that **do not** support the war. You should always keep a clear mind and look at things from a neutral perspective, especially if you're the maintainer of a repository like this. (Nr. 4)

And to be clear, I am using 7-Zip over WinRAR myself, yet I still don't think it should be on the list.

**Comment by vshymanskyy** [comment]
WinRAR was removed, by the way

**Comment by webknjaz** [comment]
> Not every Russian supports what's currently going on. We can't put them all into the same drawer.

This here is a typical whitewashing that the ruscist propaganda uses. Even if something is possible and there's like 0.001% matching cases, it doesn't matter because it doesn't change anything. Such statements only help the terrorists. There's shared responsibility, it touches everybody by definition.

Here's a quote by A.R. Moxon that describes this quite precisely:

“Historians have a word for Germans who joined the Nazi party, not because they hated Jews, but out of a hope for restored patriotism, or a sense of economic anxiety, or a hope to preserve their religious values, or dislike of their opponents, or raw political opportunism, or convenience, or ignorance, or greed.

That word is "Nazi." Nobody cares about their motives anymore.”

**Comment by lwd-temp** [comment]
> > Not every Russian supports what's currently going on. We can't put them all into the same drawer.
> 
> This here is a typical whitewashing that the ruscist propaganda uses. Even if something is possible and there's like 0.001% matching cases, it doesn't matter because it doesn't change anything. Such statements only help the terrorists. There's shared responsibility, it touches everybody by definition.
> 
> Here's a quote by A.R. Moxon that describes this quite precisely:
> 
> “Historians have a word for Germans who joined the Nazi party, not because they hated Jews, but out of a hope for restored patriotism, or a sense of economic anxiety, or a hope to preserve their religious values, or dislike of their opponents, or raw political opportunism, or convenience, or ignorance, or greed.
> 
> That word is "Nazi." Nobody cares about their motives anymore.”

According to some reports, Russians will be jailed or persecuted for anti-war speech.

Politics and war are always difficult and disgusting, especially in dictatorships.

It's hard to find a solution that's fair to everyone.

**Comment by IlliaTsarenko** [comment]
> > > Not every Russian supports what's currently going on. We can't put them all into the same drawer.
> > 
> > 
> > This here is a typical whitewashing that the ruscist propaganda uses. Even if something is possible and there's like 0.001% matching cases, it doesn't matter because it doesn't change anything. Such statements only help the terrorists. There's shared responsibility, it touches everybody by definition.
> > Here's a quote by A.R. Moxon that describes this quite precisely:
> > “Historians have a word for Germans who joined the Nazi party, not because they hated Jews, but out of a hope for restored patriotism, or a sense of economic anxiety, or a hope to preserve their religious values, or dislike of their opponents, or raw political opportunism, or convenience, or ignorance, or greed.
> > That word is "Nazi." Nobody cares about their motives anymore.”
> 
> According to some reports, Russians will be jailed or persecuted for anti-war speech.
> 
> Politics and war are always difficult and disgusting, especially in dictatorships.
> 
> It's hard to find a solution that's fair to everyone.

There no anti war protests of russians outsiside of russia because the majority of them support or fine with it. Such as they supported annexation of Crimea or parts of Georgia. Thats why everything russian should be sanctioned.
