### ISSUE TITLE
United24

### ISSUE THREAD

**Issue by robertvazan** [vshymanskyy/StandWithUkraine#139]
What is your opinion of [United24](https://u24.gov.ua/)? It seems to be designed to ease donations. Should it be listed alongside or instead of the national bank links? One obvious downside is that it loads slower than NBU pages.

**Comment by vshymanskyy** [comment]
I think we should include it as an alternative

**Comment by webknjaz** [comment]
Ref https://github.com/vshymanskyy/StandWithUkraine/pull/144
