### ISSUE TITLE
🇸🇪 SKF stops operating in/with Russia 

### ISSUE THREAD

**Issue by DennisMajvall** [vshymanskyy/StandWithUkraine#141]
Here's [the press-release from 22 Apr](https://www.skf.com/se/news-and-events/news/2022/2022-apr-22-skf-har-beslutat-att-lamna-ryssland-4243414).

Summary translated:
When the invasion began we stopped exporting to Russia. Now we've also decided to stop all business, engagements and investments with russia.

I suggest removing them from [other companies to avoid](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/Boycott.md#other-companies-to-avoid)

**Comment by vshymanskyy** [comment]
:heart:
