### ISSUE TITLE
Add mudfish.net to boycott list

### ISSUE THREAD

**Issue by U-siro** [vshymanskyy/StandWithUkraine#149]
They providing VPN services, with Russia servers ( server list is available on https://mudfish.net/server/status )
I submitted ticket about this ( https://forums.mudfish.net/t/topic/59427 ), but they ignored it.
I think that mudfish.net should added to boycott list.

**Comment by vshymanskyy** [comment]
@U-siro thanks for your attention and support.
This one is a bit tricky to decide, as VPNs can be used by russian people to access information (seeking truth, hopefully).
So I would not suggest boycotting VPNs unless they are proved to be evil.
