### ISSUE TITLE
Azov Regiment is also neo-nazi

### ISSUE THREAD

**Issue by Qizhen-Yang** [vshymanskyy/StandWithUkraine#150]
![lQLPJxaKjVxG-G3NA2_NArKwhqGwj_5SGmwC5BH5k0BUAA_690_879](https://user-images.githubusercontent.com/68524956/181874857-c5a01511-8df3-491a-bc20-4cace85e08e6.png)

**Comment by Qizhen-Yang** [comment]
I don't see the point of fighting "Russia nazi" by supporting a neo-nazi regiment.
The Azov Regiment has participated in torture and war crimes, but now incorporated into the national guard of ukraine.
The Ukrainian government is standing with nazi now, and if you say that you are against this, I support you.

**Comment by Qizhen-Yang** [comment]
I don't see the point of fighting "Russia nazi" by supporting a neo-nazi regiment.
The Azov Regiment has participated in torture and war crimes, but now incorporated into the national guard of ukraine.
The Ukrainian government is standing with nazi now, and if you say that you are against this, I support you.

**Comment by Aleksandr-yask** [comment]
Where is the tag "typical-ukrainian-nazi"?

**Comment by Qizhen-Yang** [comment]
I don't think Ukraine with Nazi troops can accuse Russia of Nazi behavior.

**Comment by Qizhen-Yang** [comment]
Well @cristaloleg, you reacted with thumbs down emoji under every comment from me.
What do you mean?
Do you support the Ukrainian nazi?
Ukraine is not going to do you any favors for having Ukraine as your father.

**Comment by cristaloleg** [comment]
Downvoting 'cause most of ukrainians nazi posts are forced by pro-russian media. I'm not going to poke dead horse here.

Simple check: if all all or most of the ukrainian forces are nazi, why do Israel help Ukraine?

**Comment by vshymanskyy** [comment]
There's nothing to discuss here.
