### ISSUE TITLE
Remove Metro from the boycott list

### ISSUE THREAD

**Issue by newlord-32** [vshymanskyy/StandWithUkraine#151]
Hello,
I just saw while looking at the site that Metro is also listed. They support Ukraine with food and fonds. So please do better research in the future before blacklisting such huge companies. 

You can also look here:
- https://www.metro.de/service/ukraine
- https://www.metroag.de/westandwithukraine

Best greetings from germany.

**Comment by stenginaut** [comment]
@vshymanskyy is the man to decide.

**Comment by vshymanskyy** [comment]
Thanks for pinging, I missed this issue!

**Comment by vshymanskyy** [comment]
Done

**Comment by vshymanskyy** [comment]
Sorry, it took so long...
