### ISSUE TITLE
Ukraine ‘endangers civilians’ with army bases in residential areas, says Amnesty

### ISSUE THREAD

**Issue by jimkey0** [vshymanskyy/StandWithUkraine#153]
add also this info:
https://www.theguardian.com/world/2022/aug/04/ukraine-civilians-army-bases-amnesty-russia-war

**Comment by cristaloleg** [comment]
https://www.axios.com/2022/08/06/amnesty-international-ukraine-leader-resign-report

**Comment by webknjaz** [comment]
> issue created 13 hours ago

> account created 13 hours ago

Clearly, it's a ruscist bot.
