### ISSUE TITLE
Оновити інфо про БД "ПЖ" (rm non-lethal)

### ISSUE THREAD

**Issue by aaabramov** [vshymanskyy/StandWithUkraine#163]
БФ "ПЖ" вже не перший місяць займається постачанням в т.ч. і летальної зброї та має на це відповідні дозволи. Думаю, все і так це знають)
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/11317222/193609974-cd9bea9f-30f0-426c-9c95-d28bccd6c8c7.png">

Пропоную прибрати хоча б акцент на тому, що донати йдуть на "**non-lethal** equipment", так як це вводить в оману.

**Comment by webknjaz** [comment]
Мені здається, що вони досі на сайті так пишуть. Може як оновлять, то й нам треба.
