### ISSUE TITLE
Using frameworks supported by Russian institutions

### ISSUE THREAD

**Issue by gilfernandes** [vshymanskyy/StandWithUkraine#166]
Hello,

I just wanted to know if it is OK to use frameworks like https://pypi.org/project/etna/ from your perspective. This specific framework is supported by https://tinkoff-group.com/ which seems to be a Russian institution.

Many thanks

**Comment by vshymanskyy** [comment]
It's directly associated/coupled with `Tinkoff.ru` so I'd suggest boycotting it.
