### ISSUE TITLE
Why the boycott list?

### ISSUE THREAD

**Issue by Yaron-Ha** [vshymanskyy/StandWithUkraine#169]
Why compose a list of general Russian companies to boycott?
What does the average citizen or business holder in Russia have to do with the conflict? They don't want this idiotic war either, and boycotting them won't hurt Putin or his army, only the already struggling Russian citizens. This list should only contain businesses directly related to the government, military or Putin.

**Comment by cristaloleg** [comment]
Due to silent support of Putin's regime for ~20years.

**Comment by Yaron-Ha** [comment]
> Due to silent support of Putin's regime for ~20years.

You realize Russia isn't a democracy with free speech, right?
The average business owner can't go on visible protest without having their business destroyed by the government and get themselves thrown in jail.

You wouldn't do anything different if you were in their place.

**Comment by qtvhao** [comment]
<img width="916" alt="Screen Shot 2022-10-21 at 12 35 36 PM" src="https://user-images.githubusercontent.com/13049357/197120662-9a60bbfb-da8f-4714-8618-19d399299ce3.png">
Because it's not false.

**Comment by Yaron-Ha** [comment]
> <img alt="Screen Shot 2022-10-21 at 12 35 36 PM" width="916" src="https://user-images.githubusercontent.com/13049357/197120662-9a60bbfb-da8f-4714-8618-19d399299ce3.png">
> 
> Because it's not false.

What isn't false?

**Comment by Yaron-Ha** [comment]
How the fuck does "typical-russian-nazi" apply here?
Not only am I not Russian but I also support Ukraine. Just not this stupid boycott. Though to be fair seeing this repo makes me doubt my beliefs about the war.

**Comment by vshymanskyy** [comment]
@Yaron-Ha Huge part of your reasoning is dictated by the russian propaganda. Thus, "typical-russian-nazi" applies here.

**Comment by Yaron-Ha** [comment]
> 

I don't read any Russian media at all. And this isn't about Russia, this is about y'alls boycott list for uninvolved Russian companies.

**Comment by jdreesen** [comment]
There is no such thing as an "uninvolved Russian company". If you are not against the war, you are for it.

**Comment by Yaron-Ha** [comment]
> There is no such thing as an "uninvolved Russian company". If you are not against the war, you are for it.

You realize being "against the war" will mean your company will be terminated by Putin and your life will be at high risk?
Seriously bro, what do you expect them to do? Tell me.

**Comment by vshymanskyy** [comment]
What do you expect me to do, if my neighbours are raped, and my house is
burned down by (ordinary) russians? I barely escaped.

**Comment by jdreesen** [comment]
I expect them to stand up against Putin and his dictatorship.

**Comment by Yaron-Ha** [comment]
> I expect them to stand up against Putin and his dictatorship. Either way, they must bear the consequences for his actions.

Would you, as a Russian businessowner, stand up against Putin, knowing that would mean likely death?

**Comment by vshymanskyy** [comment]
@Yaron-Ha yes, and Ukraine showed it by it's own example.
Do you also suggest that Ukrainians should not fight back?

**Comment by Yaron-Ha** [comment]
> @Yaron-Ha yes, and Ukraine showed it by it's own example. Do you also suggest that Ukrainians should not fight back? (fighting back also means death for a lot of us on the front line)

I said Ukrainians shouldn't fight back?
Also the same question is directed for you. Would you, as a Russian businessowner, stand up against Putin, knowing that would mean likely death?
Simple yes or no would suffice

**Comment by vshymanskyy** [comment]
> yes, and Ukraine showed it by it's own example.

this is a direct (and not hypothetical) answer to your question. read about https://en.wikipedia.org/wiki/Revolution_of_Dignity

**Comment by Yaron-Ha** [comment]
> > yes, and Ukraine showed it by it's own example.
> 
> this is a direct (and not hypothetical) answer to your question. read about https://en.wikipedia.org/wiki/Revolution_of_Dignity

Then losing your life for void is your decision. You can't expect other people to follow the same decision. As much as I support Ukraine, if I lived in Russia, I wouldn't dare voicing my opinion in public, besides very close groups with people I trust. In this scenario, should I be boycotted?

**Comment by jdreesen** [comment]
Yes.

**Comment by jdreesen** [comment]
No. You do!

**Comment by webknjaz** [comment]
> How the fuck does "typical-russian-nazi" apply here?

Duck typing, if you will. If you repeat even small bits of the ruscist excuses for committing genocide, this calls for similarity. Hence, to be labeled this way, you don't have to have a specific nationality or geographical location — just to behave like one.


> I also support Ukraine

And no, saying that “I support Ukraine” does not contradict this. Such claims are a geopolitical version of “I have a black friend, so I can't be racist” which is a logical fallacy at best.

For example, this repository is made and maintained by Ukrainians. By saying that we don't know what we need, you're participating in westsplaining (often spread by r*ssians) and basically minimize our needs. You say that you're uncomfortable with what we actually need and suggest your idea of what we should be thinking. This 100% aligns with the r*ssian thinking. Even their so-called “opposition” promotes the same views.
