### ISSUE TITLE
Is that a scam?

### ISSUE THREAD

**Issue by mvolkov** [vshymanskyy/StandWithUkraine#180]
Being from Ukraine myself, having extended family in Kiev, I can attest that nobody among people I know personally have received any sorts of help. So where all those donations go? Is that yet another speculation on the deep personal feelings?

**Comment by vshymanskyy** [comment]
What is the purpose of your comment?

All of the included Charity NGOs provide some form of reports of their expenses.

**Comment by vshymanskyy** [comment]
Agree
