### ISSUE TITLE
Serious question. How is boycotting innocent Russian businesses the right thing?

### ISSUE THREAD

**Issue by 825i** [vshymanskyy/StandWithUkraine#187]
.

**Comment by webknjaz** [comment]
Your behavior might be okay on the land of the ruscist terrorists but not here so I'm labeling this as requested.

P.S. If anyone wants to see what was in the original post the OP removed themself to hide their behavior, I can forward the GH notification but I don't see the need to republish that piece of hateful text here. It solely consists of combination of propaganda spread by a typical genocide apologist mixed with a number of personal insults.
