### ISSUE TITLE
Commission to advertise StandForUkraine

### ISSUE THREAD

**Issue by Cholowao** [vshymanskyy/StandWithUkraine#191]
I would like to know if I can earn some commission if I advertise this banner on my project or website...

I have a website with good traffic, if is there a way I can put affiliate link, or if someone is selling merchandise I can do affiliation..

Thanks in advance.

**Comment by jdreesen** [comment]
You earn moral commission if you do. I don't think there's a monetary one.

**Comment by webknjaz** [comment]
I wouldn't bother interacting. The OP just posted a bit of ruscist propaganda on a neighboring issue: https://github.com/vshymanskyy/StandWithUkraine/issues/181#issuecomment-1366024485. It's spam at best, so I'm going to label the issue based on the overall behavior on the tracker. No excuses for speading this kind of terrorism here.
