### ISSUE TITLE
remove Telegram from the list of risky software

### ISSUE THREAD

**Issue by szamanr** [vshymanskyy/StandWithUkraine#200]
Telegram should be removed from the list of potentially risky software for several reasons.

1. no E2E encryption argument makes no sense

so you're advocating for non-e2e-encrypted software like Slack and Teams, but against Telegram, supposedly because it's not e2e-encrypted? seems like double standard to me.

note that Telegram does offer E2E encryption, albeit not by default. it is as secure as whatsapp, which has sham E2E encryption - chats are encrypted, but automatic backups stored on the servers are not - that's why you can access you chat history when you get a new phone. secret chats on Telegram are as secure as signal.

2. claims of Russian ties are absurd if you actually read about Telegram history

https://www.wikiwand.com/en/Telegram_(software)#History

Pavel Durov was forced to leave Russia and fired from VK after he refused to provide users' data to the Russian government. he started Telegram in Berlin and was later moved to Dubai. it does not pay taxes in Russia has no ties to Russia.

> In 2014, Pavel Durov fled the country after allies of the Kremlin took control of the social networking site most know just as VK. Russia's intelligence agency had asked Durov to turn over the data of anti-Kremlin protesters. Durov refused to do so.

([source](https://www.npr.org/2022/03/14/1086483703/telegram-ukraine-war-russia))

Durov also has Ukrainian origins and family in Ukraine.
https://t.me/durov/156
https://t.me/durov/179

3. Telegram is a major source of independent news about Ukraine for Belarussian and Russian opposition (e.g. Nexta). 

> it is one of the few places Russians can access independent news about the war.

> "Russians are really disconnected from the reality of what happening to their country," Andrey said. "So Telegram has become essential for understanding what's going on to the Russian-speaking world."

([source](https://www.npr.org/2022/03/14/1086483703/telegram-ukraine-war-russia))

Russia has even blocked access to Telegram in the past for failing to provide users' data to the state: 
https://www.wikiwand.com/en/Blocking_of_Telegram_in_Russia
https://www.wilsoncenter.org/blog-post/russias-war-telegram-and-what-it-tells-us-about-russian-politics

**please remove Telegram from the list of risky software.**

PS. i wanted to post this in a similar thread, but that one is closed: https://github.com/vshymanskyy/StandWithUkraine/issues/104

**Comment by vshymanskyy** [comment]
Please stop posting this manipulative bs:

> advocating for non-e2e-encrypted software like Slack and Teams, but against Telegram

...we're not advocating for Slack or Teams.
