### ISSUE TITLE
Enforce HTTPS to redirect

### ISSUE THREAD

**Issue by shoonia** [vshymanskyy/StandWithUkraine#205]
Redirects are going to HTTP instead of HTTPS

from https://vshymanskyy.github.io/StandWithUkraine/ redirect to http://stand-with-ukraine.pp.ua/

Enforce HTTPS, Docs: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by webknjaz** [comment]
@vshymanskyy could you take a look at this?

**Comment by jemartin-r7** [comment]
Better to http://en.kremlin.ru/

**Comment by lganzzzo** [comment]
@vshymanskyy 

Please change redirect location to https://stand-with-ukraine.pp.ua/

Landing on non-HTTPS page scares people off of the page.

**Comment by vshymanskyy** [comment]
Sorry, yes, let's figure it out

**Comment by vshymanskyy** [comment]
Done
