### ISSUE TITLE
Answering @xamidi

### ISSUE THREAD

**Issue by ink-splatters** [vshymanskyy/StandWithUkraine#206]
>  I find it amazing how much diplomacy some people use in order to call others out on their xenophobic and/or racist statements.
But not in a good way, since calling it only a "dick stance" is quite an understatement.

> Apparently, several individuals here are lacking basic ethical understandings, so I think that unfortunately the following needs to be said.

> - Judging individuals not based on their behavior but on traits that they didn't decide for themselves (like skin color or place of birth), is unethical and baseless.
> - Individuals cannot be blamed for the actions of another individual only because they share ethnic properties.
> - Being Russian is not reprehensible. Supporting Putin (or literally any other murderer) is.
> - Dropping statements like "The fact he lives outside of Russia doesnt change the fact he is still russian" — while implying that companies supporting them per se shouldn't be supported — is racist and/or xenophobic.
> - The fact that the government of some country is a bunch of violent sociopaths doesn't make you less of a racist and/or xenophobe for discriminating against people from that country in general.
> - Many Russians didn't choose war and are in fact against invading other countries and against murder (like all sane individuals), but they had no power to avoid this. The issue in general is the actions of a few individuals.
> - It is a common problem in our systems with social hierarchies that powerful individuals do reprehensible things that the powerless masses cannot avoid. Regardless of illusions being created by elections and such.

> I didn't think I'd stumble across such a despicable display of terrible education on a network about software development.
All it takes is to combine a little unbiased observation with some logical thinking, and the above statements become rather obvious.

>Notably, your collectivist way of thinking is common with individuals that have been mentally crippled by governments via their school systems in order to be submissive and put social conventions above rhyme and reason. Which, ironically, is how wars can happen at all, instead of being shut down by people enforcing reasonable self-justice against the actual perpetrators, like Putin. Because those few who'd have the opportunity to change things for the better usually lie in mental chains.

_Originally posted by @xamidi in https://github.com/vshymanskyy/StandWithUkraine/issues/181#issuecomment-1463190398_

**Comment by ink-splatters** [comment]
@xamidi as I’m beyond any tolerance in the former issue and cannot comment there (lol), I’d like to thank you for expressing a reasonable thoughts and share a bit of mine.

I don’t care too much especially after some time has passed, what judgements are being piled on me.

I hope archive.org will scrap my comments before them likely to have being removed by the authors of this repo.

This theatre of absurd should become accessible for any spectator or better - for ones acting out of honesty and reason, who would make people aware what conglomeration of disgust has been fostered here and sold under 
#StandWithUkraine movement tags.

I know some Ukrainian guys, a few of them quite closely as colleagues / ex colleagues and I’m convinced this repo should NOT represent 

#StandWithUkraine movement as: regardless of myself, my interests and concerns whatsoever, @wojtekxtx campaign dishonours also the people of Ukraine who not only emphasise acting lawfully, appropriately, selflessly, bravely to defend their land to the very last piece of it, in uncompromising way, but also do deliver what they claim doing, backing their loved ones, their identity, their culture.

Ukrainians I know are really decent guys and it’s absolutely natural to respect them. Most part my life I’ve had dozens of direct contacts, my personal life was linked to Ukraine back then, my mother’s life as well as she was postgraduate in Kyiv.

I consider Ukrainian culture, mentality, language (which I understand but don’t speak fluently) close to how I perceive things, my attitude, and what values I do have, those values have been never imposed on me unnaturally or artificially but are the result of solely live experience.

it’s worth mentioning that @wojtekxtx is not Ukrainian and positions himself as volunteer from Poland who was shocked of “what Russians do”.

 I haven’t for a blink of an eye had intent to diminish his volunteering activities being obviously very humane and right.

Still the very questionable behaviour of @wojtekxtx given #StandWithUkraine tag which I already mentioned, might promote his thoughts as of Ukrainian and looks very unfair to actual Ukrainian guys who I know and who I don’t know but may conclude via 3rd parties ; and who all share a common trait: they would never ever be involved in such a gross, low bar hate speeches. 

WhT is sad is that @vshymanskyy as the owner sadly tolerates this kind of rhetorics and the visibility of the platform and #standforukraine doesn’t come in between.

@vshymanskyy you have public accounts in social networks. Your country was  treacherously invaded; what Russian war criminals commit is vile and inhumane even for war times. Ukraine is unambiguously and clearly injured party taken a call to withstand the bleeding edge fascism and Heroes of your country put give their lives for the land, for the beloved, for their values. 

You as people do have Purpose and that’s why your warriors fight so brave, selflessly and heroically, and among political establishment and practical interests of your allies, it’s clear that that scale of support is thanks to what you have achieved and how you have presented yourself to the world.

I believe I had expressed my respect sincerely.

I clearly see this repo a strong impulse aiming practical impact of seizing the financial flows of war dogs. I don’t have a doubt you are true patriot of your country.

I just want to say that apart from me personally the content your host undermines the good name of the movement.

You are not up to listening me as  one born at the side of your perpetrators? That’s too good.

Just try mental alignment with what Ukraine sticks to in terms of the values it presents. 

The racism and exclusion seen here to my mind cannot be acceptable and while people of Russia are responsible their individual responsibility is limited by law. 

I do hope the bastards if not eliminated come here to Den Haag to stand trials and prepare for the most isolated Колыма in the world.

Please do check the reality and make your decision whatever it is.

Thanks everyone.

**Comment by webknjaz** [comment]
> cannot comment there

And yet, you commented there with an attempt to insult me using google translate, I received the email notification, after which you removed your comment to pretend you haven't just proven my point about the behavior of the ruscists.

> I hope archive.org will scrap my comments before them likely to have being removed by the authors of this repo.

I'm not aware of any comments being removed by us. Moreover, we sometimes trigger web.archive.org captures to document the real behavior of the ruscists here.

So it's either you trying to pretend not to be one (spoiler alert: you failed), or maybe GitHub somehow detects insults/abuse and deletes it (though, I'm only aware of cases where such comments are cleaned up by them after detecting bot accounts with the only purpose of posting insults all over the place).


Anyway, I'm closing this spam too. You've been nothing but insensitive in this repo so there's no reason for us value any of your words.

**Comment by xamidi** [comment]
@webknjaz It is just ridiculous either how clueless you are about how truth works, or how delusional you consider readers to be.
You seriously called me "probably trolling" in that thread, after I ripped your misinterpretations and poor attempted arguments apart. Yet you continue to project your own totalitarian views (which come from a place of blind compassion rather than thoughtful conscientiousness) on other people. This kind of black-and-white thinking is a very typical thing for "politically correct" people to do, since it puts them in many ways into the easiest place to be.
But that doesn't make it right. It makes you a horrible and intellectually lazy person that is presenting itself to be virtuous, while blatantly telling anti-truths, i.e. statements which couldn't be further from the truth.

**Comment by xamidi** [comment]
@webknjaz It is just ridiculous either how clueless you are about how truth works, or how delusional you consider readers to be.
You seriously called me "probably trolling" in that thread, after I ripped your misinterpretations and poor attempted arguments apart. Yet you continue to project your own totalitarian views (which come from a place of blind compassion rather than thoughtful conscientiousness) on other people. This kind of black-and-white thinking is a very typical thing for "politically correct" people to do, since it puts them in many ways into the easiest place to be.
But that doesn't make it right. It makes you a horrible and intellectually lazy person that is presenting itself to be virtuous, while blatantly telling anti-truths, i.e. statements which couldn't be further from the truth.
All while attempting to silence those who speak truth.

**Comment by ink-splatters** [comment]
> > cannot comment there
> 
> And yet, you commented there with an attempt to insult me using google translate, I received the email notification, after which you removed your comment to pretend you haven't just proven my point about the behavior of the ruscists.


It's myself attempted to insult you, for which I sincerely apologise as I do believe that it's not a reaction one can be proud of. It cannot be justified by it, but the reason for that is I was severely affected emotionally, the level I could not hold it with myself. It just could not be processed by me, back then, why @xamidi deserved the treatment you gave to him. 

As for myself, I believe it's not appropriate to insult people this way, this was the reason I withdrew the comment, as it looked ugly. Important, that my point of view has not changed.

A few points: 

1. I essentially disagree with @xamidi regarding the warfare supply to Ukraine: in the end I live in EU country and technically contribute to supplying warfare to Ukraine via taxes and acknowledge I pay for this supplies, _and_ I believe this is the only way for Ukraine to win 
as it's evident and I confirm as being quite aware about things, that no doubts all the opportunities for peace have been exhaused in the face of horrific amount of war crimes by Ru army.

The scary thing, @xamidi, is also that people are being treated hardly better than broiler chicken who's the only purpose you know. Thy come again and again, die, they fill up trenches with dead bodies and another portions go on top, there are quite a few films about zombies, but the zombie virus is nothing but propaganda; that's the case and it has been the case, it's just very prominent example, since maybe World War II.

2. @webknjaz  I don't thing you would care, in terms that it's delivered to you by me, and not someone else, this places `com.apple.quarantine` equivalent on it;  on the other hand why not trying(not really hard):

I believe you are reasonable, smart guy according to your profile, yet you cannot accommodate anything, currently, which doesn't fit your way of thinking, in relation to the war. I personally don't have zero anger (at this moment, not back then), no grievance or feeling injustice to me or anyone else on your behalf or on behalf of your like-minded people.

The only I really do feel is deep sadness, at some moments - dark sadness.

You cannot be blamed for your behaviour such as sticking nazi label,  which infuriated me to the point I broke and spewed what you got in your notifications.

And I don't have a "right to feel offended" by a person, people of who's country have been suffering for more than a year, in the end @webknjaz I don't know and would not of course rule out unfortunate possibility that war was too close to you personally, your friends, loved ones, by which I mean - being directly impacted - physically and/or emotionally, effectively getting PSTD symptoms.

--
The same way it doesn't justify my behaviour you witnessed, I felt what I feel, either having a "right" for it or not. That's how feelings work. I still believe @xamidi doesn't deserve for a second the nazi sticker to be sticked on him. It's just he doesn't.

And you are not to be blamed for that you fail to model his line of thoughts in the way it wouldn't have made him "nazi" in your eyes/ be excluded and humiliated.

As much as you are not to be blamed, the same much is it miserable to observe. It's sad. It's fucking tragedy for _peoples of countries_, also beyond Ukraine and Russia. I cannot believe you cannot comprehend this, don't you? Isn't fucking tragedy?

This WILL get new wave of extremism to be born, it's nothing to do with neither my point of view, nor with yours, it's just how hatred works: though it's appropriate response in your case, still the level is that insane that you guys won't make out of this undamaged. It's good if you can, but it's how human psyche works and one doesn't need to be a shrink with PhD in Clinical Psychology in order to say this.

You haven't chosen Russians to hate, as Hitler (sorry) chose jews to hate, instead these are some Russians who chose Ukraine to become ruined with later on ceasing to exist whatsoever.

Good. And what?

What I want to say: the same way hatred is natural to have for you and your people, it cannot come up with creations which would exclude it, hatred itself: the hatred inevitably will be there in anything it builds.

Is it then a big deal, that someone's hatred is justified and someone's not really? 

I don't believe so. There is not so much difference.

It's evident that hatred defeats logical thinking in the way it promotes cutting off "conditional branches" in one's head head, kind of, which are marked as `com.apple.quarantine` xattr (let me use a bit of swear words, which I'm sure you understand),in particular I mean:

anything which disputes / questions the right of Ukraine and its people to have the only and indisputable truth about the war, about the position they occupy in this war, how they treat anyone else's position, and axiomatic role of Russians in the conflict - faces automatic armed response, in the case of GitHub issue, via saying by mouth (= typing with fingers).

All the "good" and "truth" which is not sufficiently good or true are to be discarded immediately, in many cases with hardly giving a chance to one to elaborate their point.

It's clear why. It doesn't help though. It's sad that you don't seem to aim while shooting. "Friendly Fire" is as shabby expression as it asks for itself to be put here.

-- 
What to do? (c) I don't know if this can be changed. Ukrainian guys who I approach, and I try my best to always approach from the position of reason and respect, given we are not acquainted and there is not any evident reason for otherwise; and they just either let me in their circle or don't and - that's it, that's probably how it works, right?.. There is a bit of bias but I'm thankful that not so much, given the expat community is inherently very interconnected. And if you say wan't to help, as we were gathering some stuff to be sent to Polish border, you just meet people. This is besides Ukraininan colleagues of course.    

PS: I did use Google translate to help with what you received in the Notification; as that's what I felt on that moment and it was very aligned with my feelings.

It's not showing off strictly, well it wasn't without arrogance bit, but I didn't want to use English and the worst idea I thought would've been using Russian.

I had a Ukrainian partner, so I speak the absolute basics of Ukrainian and can understand the most, still my level especially in writing is below intermediate. 

I posted somewhere in your issues, that I respect and love Ukrainian culture, I grew up being very much close to Ukrainian music, from my mom having her thesis defense in Kyiv,  Вокарчук's Океан Ельзи, 5nizza, etc. to Pussy Grinder (LOL) (those came to my city in some 2004, if you know who they are).
Besides I know personally quite a few of great people.

That's why it's all very personal tragedy in both ways it's _happening_, it's such a disaster, which is unnatural, but is committed against the whole nation; the second part is less of a tragedy but as I said - it makes me sad very much, that I'm inevitably part of this story, and I'm to get what is to be given to me thanks to my origin, there is not a problem with it. The problem that even If acknowledge things and take the responsibility, it hurts a lot that it doesn't practically change anything in one's attitude, it's already there: either you are let in or not.

**Comment by xamidi** [comment]
> 1. I essentially disagree with @xamidi regarding the warfare supply to Ukraine: in the end I live in EU country and technically contribute to supplying warfare to Ukraine via taxes and acknowledge I pay for this supplies, _and_ I believe this is the only way for Ukraine to win
>        as it's evident and I confirm as being quite aware about things, that no doubts all the opportunities for peace have been exhaused in the face of horrific amount of war crimes by Ru army. The scary thing, @xamidi, is also that people are being treated hardly better than broiler chicken who's the only purpose you know. Thy come again and again, die, they fill up trenches with dead bodies and another portions go on top, there are quite a few films about zombies, but the zombie virus is nothing but propaganda; that's the case and it has been the case, it's just very prominent example, since maybe World War II.

We do not disagree there in the slightest, not sure where you got that impression. I would go kill Putin or the invaders myself if I was in any good position to do so. And I support the victims of such crimes to be provided with means to defend themselves.

I just didn't make this a topic of my previous comments, but my point was that there are also racists and xenophobes that stand with Ukraine, which notably includes contributors to this repository. And I dislike that because these individuals are making the movement decomposing itself into the very thing it stands against.
