### ISSUE TITLE
Paypal takes 5 months to transfer money to Ukraine

### ISSUE THREAD

**Issue by evlquaker** [vshymanskyy/StandWithUkraine#21]
@vshymanskyy I tried to donate to Army SOS as you recommended, but I made the mistake of using PayPal. After I submitted payment PayPal stated the money will not be available until September 5th! PayPal will not let me cancel. Please make people aware so they can use a different payment method. Best wishes for you and your family. I am a big fan of Blynk.

**Comment by vshymanskyy** [comment]
Thank you, fixed!

**Comment by evlquaker** [comment]
@vshymanskyy I just spoke with Army SOS and they actually received the Paypal transfer almost instantly. Paypal just had a very misleading message. Sorry for the mistake.
