### ISSUE TITLE
Don't lie mate

### ISSUE THREAD

**Issue by 825i** [vshymanskyy/StandWithUkraine#211]
Lol don't lie, you don't have shit.

https://github.com/vshymanskyy/StandWithUkraine/issues/187#issuecomment-1356266729

What about all the Ukrainian soldiers who have raped and murdered and tortured Russians during the war and the videos of Ukrainians cutting off solider's testicles?

Imagine losing your entire country because you picked a fight with neighbor who has 100x the population, resources and money, and thinking that the US propaganda and the rest of the world are going to bail you out. Especially when you declined to join NATO like 5 times previously. You picked a fight with one of the largest and most well stocked nations on earth (Russia) and they are next to the actual largest and most well stocked nation (China).

Like it or not, less and less people care about anything happening in Ukraine every day. You wouldn't have last 5 seconds without the 1+ trillion in foreign aid and even everyone's money and patience is truly drying up now.

You can see outside of USA and EU, no one cares: https://www.ifw-kiel.de/topics/war-against-ukraine/ukraine-support-tracker/

Your stupid leader had one job and one job only. To PREVENT war. To make a decision where not a single life would have been lost. Instead you live with the daily reminder that your country will likely never economically and emotionally recover whilst most people have taken their cash, moved to Poland or elsewhere, spent their money there on foreign investments and will probably never return to the ruin your country has become.

Sad that you bring your politics into open source platforms. Your idiot leader has reduced your people to begging online.

When the dust has settled, there will be plenty of time for people to learn of the war crimes of Ukraine.

You want to stop the war? Write to your stupid manlet president and tell him to stop asking for more bombs and rockets and to start talking of peace.

**Comment by 825i** [comment]
Also I forgot to ask. How come you're hiding in CZ whilst the rest of your countrymen are fighting?

**Comment by webknjaz** [comment]
Per https://github.com/vshymanskyy/StandWithUkraine/issues/187#issuecomment-1356266729 I can also provide the screenshots of this same individual from their earlier post, showcasing a typical ruscist behavior in all of its aspects (like lying that I might not have those :clown_face:). In private, of course, since I don't want to give the terrorists a platform.
