### ISSUE TITLE
Clarification Request: How are these companies affiliated with Russia?

### ISSUE THREAD

**Issue by Announcement** [vshymanskyy/StandWithUkraine#226]
AFAIK at least a few of these companies are U.S. originating and see no obvious reason to boycott. someone help me out here?
Without this information it appears as if someone is using the list for some kind of personal agenda amongst an international war...

**Comment by Announcement** [comment]
To be clear I am not insinuation that this is the case, just a little confused as to how they are affiliated.

**Comment by jemartin-r7** [comment]
Doesn't matter.

**Comment by webknjaz** [comment]
There's a link to https://www.yalerussianbusinessretreat.com/ right in that section. Operating, having any business relationships and paying taxes is enough to be on the list.
