### ISSUE TITLE
Если я молчу,- я за войну?

### ISSUE THREAD

**Issue by romazhan** [vshymanskyy/StandWithUkraine#241]

**Comment by FoggyFinder** [comment]
It seems like you're undecided whether you're war supporter or not. That's not bad already. Hopefully you will make the right choice and actually do something.

**Comment by romazhan** [comment]
Я задал конкретный вопрос, но почему-то конкретного ответа нет

**Comment by FoggyFinder** [comment]
no one except you can reply to this Q. So I think you already know the answer. And this answer is bothering you.

**Comment by romazhan** [comment]
"Do not be silent! Silence is a sign that you accept the Russian government's policy." - если никто, кроме меня, не может ответить на этот вопрос, то кто это писал? Предлагаю удалить это предложение

**Comment by FoggyFinder** [comment]
> Меня беспокоит это: "Do not be silent! Silence is a sign that you accept the Russian government's policy." 

Why it's bothering you? "Silence" is used in broad sense here. It's just an assumption and in most cases I suppose it's correct statement. Because why would someone who actually against the war does nothing when their country started one?

**Comment by romazhan** [comment]
Когда тебя заставляют чувствовать себя виноватым, когда ты ничего не сделал,- тобой пытаются манипулировать. Когда тебя упрекают как раз в твоём бездействии,- это выглядит еще более абсурдно. Согласен со мной?

**Comment by FoggyFinder** [comment]
> Когда тебя заставляют чувствовать себя виноватым, когда ты ничего не сделал,- тобой пытаются манипулировать

No one can enforce you to do anything. So you feel uncomfortable that folks think you're ruscist just because you're from Russia? 

>  Когда тебя упрекают как раз в твоём бездействии,- это выглядит еще более абсурдно. Согласен со мной?

Nope. You're wrong. Do you understand that do nothing is also a choice? That's common logic not a rocket science. You basically responsible for your country actions as well.

**Comment by romazhan** [comment]
> No one can enforce you to do anything. So you feel uncomfortable that folks think you're ruscist just because you're from Russia?
Я не из России 
> Nope. You're wrong. Do you understand that do nothing is also a choice? That's common logic not a rocket science.
Допустим я не хочу знать о ситуации в мире, так как это вызывает дискомфорт? Да, это мой выбор, но это выбор не в пользу войны. Значит ты подменяешь понятия?
> You basically responsible for your country actions as well.
Я не несу ответственность за людей, которые отдают приказы, потому что не я отдаю приказы, а другие люди, как я могу нести ответственность за человека, который отдал приказ? Я же не этот человек, который отдал приказ. Я вообще не отдаю приказы

**Comment by FoggyFinder** [comment]
>Я не из России

Но вы себя идентифицируете как россиян/русский?

> Допустим я не хочу знать о ситуации в мире, так как это вызывает дискомфорт?

Бедный половозрелый мальчик не из России чувствует себя дискомфортно из-за того что где-там далеко-далеко идет война к которой он не имеет никакого отношения. Но его беспокоит некоторые сообщения в интернете. Наверное совесть что-то нашептывает, не иначе.

Вы подумали о тех кому сейчас приходится в холод и в жару, в дождь и в снег защищать свою страну от нападения тупой орды которую заботит лишь новые территорий? О том что они теряют своих сослуживцев намного чаще чем вы можете себе представить? Думаете им просто будет адаптироваться к мирной жизни после всего увиденного и пережитого?

Вы подумали о тех кто потерял конечности и останется калекой на всю жизнь? О тех, кого уже не вернуть? И молодых и пожилых. Могли бы еще жить и жить. Но, нет, рашисты решили иначе. Даже сегодня, днем, запустили ракету по центру Чернигова и кого там волнует потерпевшие.

А о психологическом состоянии людей которые уже который год ~живут~ существуют, зная что в любой момент их дом может быть стер а жизнь оборваться?

Нет, конечно не думали. Вам плевать. Это-же далеко. Вы как и большинство россиян законченные эгоисты не способные даже на минимальную эмпатию. Зато после войны все как один запоете что мы-то уж были против а вовсе не за. Просто молча. Предпочли закрывать глаза и делать вид что ничего не происходит. Только вот никто из здравомыслящих людей вам уже не поверит.

И нет, не надо скидывать вину на Путина. Это вы его выбирали. Война началась не в 22 году, как многим кажется, а намного раньше. Так что не делайте вид что вы тут не причем. Вся Россия и есть коллективный Путин.

> Да, это мой выбор, но это выбор не в пользу войны. Значит ты подменяешь понятия?

Нет. В Африке например войны не прекращаются. Было бы лицемерием утверждать что меня сильно волнует что там происходит. Но Украина не имеет к тем войнам никакого отношения. Моя совесть чиста.
В отличие от.

**Comment by romazhan** [comment]
Вроде бы лёгкий вопрос, но какая из этого большая дискуссия 😂

> Но вы себя идентифицируете как россиян/русский?

Я на половину русский

> Бедный

Если ты кого-то оскорбляешь, это означает что у тебя нет хороших аргументов. Предлагаю использовать качественные аргументы, или изменить свое мнение.

> половозрелый мальчик не из России чувствует себя дискомфортно из-за того что где-там далеко-далеко идет война к которой он не имеет никакого отношения.

Я не сказал, что это вызывает у меня дискомфорт, ты снова подменяешь понятия. Возможно виноват переводчик?

> Но его беспокоит некоторые сообщения в интернете. Наверное совесть что-то нашептывает, не иначе.

Ты снова пытаешься манипулировать. Может быть и мальчик, но понимает когда им хотят манипулировать.

> Вы подумали о тех кому сейчас приходится в холод и в жару, в дождь и в снег защищать свою страну от нападения тупой орды которую заботит лишь новые территорий? О том что они теряют своих сослуживцев намного чаще чем вы можете себе представить? Думаете им просто будет адаптироваться к мирной жизни после всего увиденного и пережитого?
Вы подумали о тех кто потерял конечности и останется калекой на всю жизнь? О тех, кого уже не вернуть? И молодых и пожилых. Могли бы еще жить и жить. Но, нет, рашисты решили иначе. Даже сегодня, днем, запустили ракету по центру Чернигова и кого там волнует потерпевшие.
А о психологическом состоянии людей которые уже который год живут существуют, зная что в любой момент их дом может быть стер а жизнь оборваться?

Я не готов обсуждать ситуацию, так как сегодня я ел йогурт и катался на велосипеде. Я рад, что сегодня я ел йогурт, хотя мне кажется, что у меня от него изжога, а также, что сегодня я катался на велосипеде, при этом не поддерживая войну. И да, ты опять пытаешься вызвать чувство жалости.

> Нет, конечно не думали. Вам плевать. Это-же далеко. Вы как и большинство россиян законченные эгоисты не способные даже на минимальную эмпатию. Зато после войны все как один запоете что мы-то уж были против а вовсе не за. Просто молча. Предпочли закрывать глаза и делать вид что ничего не происходит. Только вот никто из здравомыслящих людей вам уже не поверит.

И да, ты опять пытаешься манипулировать. Я вроде бы написал, что я не из России. Возможно виноват переводчик?

> И нет, не надо скидывать вину на Путина. Это вы его выбирали. Война началась не в 22 году, как многим кажется, а намного раньше. Так что не делайте вид что вы тут не причем. Вся Россия и есть коллективный Путин.

Возможно ты не увидел, но я не из России, соответственно я не мог выбрать Путина. Возможно виноват переводчик?

> Нет. В Африке например войны не прекращаются. Было бы лицемерием утверждать что меня сильно волнует что там происходит. Но Украина не имеет к тем войнам никакого отношения. Моя совесть чиста.

?

**Comment by FoggyFinder** [comment]
> Если ты кого-то оскорбляешь, это означает что у тебя нет хороших аргументов.

Вы видите оскорбления там где их нет. Слово "бедный" в моем сообщении использовалось в смысле "несчастный".. Насчет вашей финансовой состоятельности я не делал никаких предположений. Не вижу как это может относится к вопросу.

> Я на половину русский

Я не спрашивал кто вы по национальности. Я спрашивал как вы себя идентифицируете?

> Я не сказал, что это вызывает у меня дискомфорт, ты снова подменяешь понятия. Возможно виноват переводчик?

Может и переводчик. А возможно вы просто безграмотны?
Раз вы пришли сюда и подняли вопрос значит вас это **беспокоит**. Обычно **беспокойство** вызывает **дискомфорт**. Нет, возможно что вы мазохист или того хуже, в таком случае я действительно поторопился с выводами.

> Ты снова пытаешься манипулировать. Может быть и мальчик, но понимает когда им хотят манипулировать.

Вам показалось. Но сильно не переживайте, с опытом придет.

> И да, ты опять пытаешься вызвать чувство жалости.

И снова вам показалось. Это уже входит в привычку. Я черным по белому написал что большинству россиян эмпатия чужда.

> Возможно ты не увидел, но я не из России, соответственно я не мог выбрать Путина. Возможно виноват переводчик?

Может быть. Я старался использоваться английский, но вы так упорно отвечали на русском что мне показалось невежливым отвечать на каком-то ином языке. Если русский для вас не родной то попробуйте все-таки найти более подходящую площадку для практики. И поднимать менее серьезные вопросы.

В последнем предложении моего прошлого сообщения есть тезис что Россия это коллективный Путин. Попробую выразиться попроще. Россияне выбрали Путина из-за того какие они есть и какими хотят быть. Образ мышления, понимаете? Не обязательно иметь гражданство России, жить в России, родится в России чтобы быть рашистом.

**Comment by romazhan** [comment]
> Вы видите оскорбления там где их нет. Слово "бедный" в моем сообщении использовалось в смысле "несчастный".. Насчет вашей финансовой состоятельности я не делал никаких предположений. Не вижу как это может относится к вопросу.

Хорошо, но что для тебя означает "несчастный"? Почему ты считаешь меня несчастным?

> Я не спрашивал кто вы по национальности. Я спрашивал как вы себя идентифицируете?

Хорошо. Я идентифицирую себя как "на половину русский"

> Раз вы пришли сюда и подняли вопрос значит вас это беспокоит. Обычно беспокойство вызывает дискомфорт. Нет, возможно что вы мазохист или того хуже, в таком случае я действительно поторопился с выводами.

Выше я писал что именно меня беспокоит. Предлагаю тебе прочитать повнимательнее, а именно "половозрелый мальчик не из России чувствует себя дискомфортно из-за того что где-там далеко-далеко идет война к которой он не имеет никакого отношения" не вызывает у меня дискомфорт. Возможно мне нужно писать более развернуто, чтобы ты смог понять

> Вам показалось. Но сильно не переживайте, с опытом придет.

С опытом я понял, что, если у тебя пытаются вызвать чувство вины, значит тобой манипулируют. Думаю с опытом поймешь

> И снова вам показалось. Это уже входит в привычку. Я черным по белому написал что большинству россиян эмпатия чужда.

И да, в предложении, на которое я ответил ты снова пытаешься вызвать чувство вины, соответственно пытаешься манипулировать

> Может быть. Я старался использоваться английский, но вы так упорно отвечали на русском что мне показалось невежливым отвечать на каком-то ином языке. Если русский для вас не родной то попробуйте все-таки найти более подходящую площадку для практики. И поднимать менее серьезные вопросы.

Ну что ты, русский мой родной язык. Вы подняли очень серьезную тему, вы предлагаете людям отказаться от больших open source проектов и компаний, я считаю, что это вам нужно найти более подходящую площадку для политических вопросов. А мой вопрос простой, если ты забыл, можешь прочитать заново

> Попробую выразиться попроще. Россияне выбрали Путина из-за того какие они есть и какими хотят быть.

Можешь отправить мне ссылку, где Путин перед выборами обещал начать любого рода войну? Если нет, получается это пустые обвинения?

Но, в принципе, ты уже ответил на мой вопрос:
> It's just an assumption

В таком случае нужно пометить "Do not be silent! Silence is a sign that you accept the Russian government's policy" как "предположение"

**Comment by FoggyFinder** [comment]
> Хорошо, но что для тебя означает "несчастный"? Почему ты считаешь меня несчастным?

Это был сарказм. А за толкованием слов обращайтесь к словарю.

> Ну что ты, русский мой родной язык. 

Значит все-таки безграмотность. Ничего не могу с этим поделать. Попробуйте читать больше книг.

> Выше я писал что именно меня беспокоит. Предлагаю тебе прочитать повнимательнее

Там так и написано "Бедный половозрелый мальчик не из России чувствует себя дискомфортно **из-за того** что где-там далеко-далеко идет война к которой он не имеет никакого отношения. Но **его беспокоит некоторые сообщения в интернете**. ".

Это довольно простая мысль и мне странно что приходится ее пояснять, но я все-таки сделаю скидку на вашу идентификацию:

Этот репозиторий был создан после полномасштабного вторжения со стороны соседнего недружественного государства. Призывы бойкотировать российские компании и проекты спонсирующие войну это лишь ответная реакция. Первопричина вашего дискомфорта лежит именно в действиях коллективного  Путина - России.

Теперь разобрались?

> Вы подняли очень серьезную тему, вы предлагаете людям отказаться от больших open source проектов и компаний

Я ничего такого не предлагаю. Если хотите знать мое мнение то я считаю что полагать что голосование ногами поддержит достаточное количество людей чтобы оказать существенное влияние несколько наивно.

> Но, в принципе, ты уже ответил на мой вопрос:

Это моя трактовка. У тех кто писал этот текст возможно другая точка зрения.
Несколько расширю свою мысль. Слова говорят громче дело. 

Некоторым людям находящимся в России банально страшно высказываться в поддержку Украины. Они боятся режима. Они могут молчать, но зато делать некоторые вещи. Например, донатить криптой людям пострадавшим от войны или на дроны, машины и так далее.. В таком случае тезис что они поддерживают войну уже не может к ним применятся. Они совершали вполне определенные действия четко показывающие что они против. Главное чтобы эти действия шли от души а не в качестве сделки с совестью.

**Comment by romazhan** [comment]
> Это был сарказм. А за толкованием слов обращайтесь к словарю.

Аа, думаю неуместный сарказм

> Значит все-таки безграмотность. Ничего не могу с этим поделать. Попробуйте читать больше книг.

Я вот не понимаю, на чем ты строишь свои выводы? Такое чувство, что ты одновременно моешь посуду и отвечаешь мне

> чувствует себя дискомфортно из-за того что где-там далеко-далеко идет война к которой он не имеет никакого отношения

Видимо мне нужно было чётко выделить тот текст, на который я отвечал. По-моему у тебя проблемы с восприятием контекста, так как уже который раз ты делаешь ошибки по поводу моих предложений, но я стараюсь отвечать максимально прямо

> Этот репозиторий был создан после полномасштабного вторжения со стороны соседнего недружественного государства. Призывы бойкотировать российские компании и проекты спонсирующие войну это лишь ответная реакция. Первопричина вашего дискомфорта лежит именно в действиях коллективного Путина - России.
Теперь разобрались?

Я все это понимаю, но вопрос связан именно с цитатой из репозитория "Do not be silent! Silence is a sign that you accept the Russian government's policy". Это утверждение является неверным и я задал вопрос, чтобы на него четко ответили,- почему, а далее мы бы уже продолжали дискуссию

> Я ничего такого не предлагаю. Если хотите знать мое мнение то я считаю что полагать что голосование ногами поддержит достаточное количество людей чтобы оказать существенное влияние несколько наивно.

Хорошо, я тоже так считаю

> Это моя трактовка. У тех кто писал этот текст возможно другая точка зрения.
Несколько расширю свою мысль. Слова говорят громче дело.

Да, я хочу узнать мнение других об этом, поэтому я не закрываю обсуждение

**Comment by FoggyFinder** [comment]
> Я не понимаю, на чем ты строишь свои выводы?

Попробуйте перечитать мои ответы вдумчиво, возможно это поможет. Но я сомневаюсь. В любом случае беседа себя исчерпала. За сим откланиваюсь. Если будет что-то интересное вернусь.

**Comment by DavertMik** [comment]
> Я задал конкретный вопрос
> Если я молчу
> Я не из России

Мне кажется вы просто самовлюбленный человек который решил поговорить о себе. Хотите поговорить о себе-любимом - аведите себе инстаграм или жену. А поддерживаете ли вы войну или нет - вам виднее. Не вижу сути для обсуждения.

**Comment by romazhan** [comment]
Да я хотел, чтобы вы немного сбавили градусы. Если я молчу, это не значит, что я за войну. Если кто-то молчит, это не значит, что он за войну. Вы просто пытаетесь вызвать чувство вины, пытаетесь манипулировать.

> Мне кажется вы просто самовлюбленный человек который решил поговорить о себе. Хотите поговорить о себе-любимом - заведите себе инстаграм или жену.

Вообще не по теме, как всегда, у вас нет хороших аргументов против.

@webknjaz , чем я тебя обидел?

**Comment by romazhan** [comment]
У вас все на эмоциях, в принципе я могу это понять и не обижаться

**Comment by webknjaz** [comment]
Looks like it's pointless to keep this open, but here's an excellent thread by @zverok that summarizes a lot of our observations: https://twitter.com/zverok/status/1760332331804463475.

TL;DR passive support is that indifference that the terrorist state relies on heavily. Silence is just one example.

**Comment by romazhan** [comment]
Сделаю выводы используя твою логику: я не поддерживаю войну, значит я "typical-russian-nazi", но если я буду поддерживать войну, то я не буду являться "typical-russian-nazi"

**Comment by webknjaz** [comment]
That's not logic but cheap manipulation.

**Comment by romazhan** [comment]
Ого, необычно видеть как украинский нацист это признает

**Comment by webknjaz** [comment]
This is not very prominently documented but that label is applied when any ruscist behaviors or traits (one or more) are observed in an issue, by the way. At any point in time, by any participant. It's just an indication that there's such a behavior to be found inside.

**Comment by romazhan** [comment]
Раз уж имя тега не имеет ничего общего с его значением переименуй его  в "ukrainian nazi"

**Comment by webknjaz** [comment]
... and you just exhibited one more of such behaviors, just like putin or navalny.

So go away, schizofascist. Nazis are not welcome here, despite your worst manipulations.

I'm locking this because you came here to justify genocide and never shown any other intentions.
