### ISSUE TITLE
Quiero donar una parte a Israel una a Ucrania y deseo por favor aunque sea 2000 dólares para seguir con mi inversión

### ISSUE THREAD

**Issue by leodanys81** [vshymanskyy/StandWithUkraine#256]

**Comment by leodanys81** [comment]
Ayudar a estos países y las personas que no tenemos sólo ganas de salir adelante

**Comment by webknjaz** [comment]
I verified with a Spanish-speaking friend that this text doesn't make much sense. The account is empty and only created one other spam-issue in another repo (https://github.com/continuedev/continue/issues/607).
So I'm closing this as spam.

_(For more context)_ Conveniently, the time of creation correlated with some ruscist troll bot activity we've seen recently, spreading antisemitic messages.
