### ISSUE TITLE
On 2023-12-30, the Ukrainians fired a missile at the Russian city of Belgorod, killing 21 civilians, of which 3 were children. 110 injured, 30 in critical condition.

### ISSUE THREAD

**Issue by Nocty1501** [vshymanskyy/StandWithUkraine#263]
This is just one of very many terror bombings the Kiev junta commits of a daily basis.

I would ask how you people live with yourselves, but that would be more of a rhetorical question at this point...

You guys are bad people :(

If you're reading this because you stumbled upon the repository and are seeking some shred of sanity in this unjust world, know that you were not the first.

No one is immune to propaganda, but some people have a healthier relationship with reality than others.

Death to Nazis.

**Comment by webknjaz** [comment]
Go away, ruscist nazi 🤡 🤡 🤡
