### ISSUE TITLE
When should we start removing the banner?

### ISSUE THREAD

**Issue by rprovodenko** [vshymanskyy/StandWithUkraine#266]
Since it's become apparent that Ukraine is rapidly failing the war, and seems obvious that the trend of talking up Ukraine is going to end soon - when would it be best to start removing the banners? It'd feel really uncomfortable to be the only one with the banner all of a sudden. Nobody wants to be the last one doing it.

Can we do it automatically somehow? Just agree on the best date and do it in an automatic way for everyone so no one gets to be the last one.

Дякую!

**Comment by webknjaz** [comment]
Since you're preaching false ruscist narratives, I'm not going to entertain the nonsense of pretending you're not a bot. But to keep it brief, the answer is to wait at least a year after ruzzia collapses and the spread of the terrorist culture fades.
