### ISSUE TITLE
JetBrains now stopped all sales in Russia and Belarus

### ISSUE THREAD

**Issue by iluuu1994** [vshymanskyy/StandWithUkraine#27]
https://blog.jetbrains.com/2022/03/11/jetbrains-statement-on-ukraine/

> Today we are announcing that we will be suspending sales and R&D activities in Russia indefinitely. Sales in Belarus are also suspended indefinitely.

Couldn't post it in https://github.com/vshymanskyy/StandWithUkraine/issues/11 since it is locked.

/cc @azjezz

**Comment by tgalopin** [comment]
I just saw this after creating https://github.com/vshymanskyy/StandWithUkraine/pull/28

**Comment by terrajobst** [comment]
It seems nonsensical to me to boycott JetBrains. They made their position clear and are following up with actions, including closing their offices in Russia.

**Comment by vshymanskyy** [comment]
This is enough to be removed from the list. As you see this was announced just today (March 11, 2022).

Thanks for letting us know

**Comment by iluuu1994** [comment]
Thanks @vshymanskyy! :slightly_smiling_face:
