### ISSUE TITLE
EPAM is staying in Russia

### ISSUE THREAD

**Issue by yevster** [vshymanskyy/StandWithUkraine#33]
**EPAM Systems is currently included in the [Boycott list](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/Boycott.md)**

Their PR communication may be lacking, but they continue posting new jobs on Russian career sites: https://career.habr.com/vacancies/1000099587 (This one is located in St. Petersburg, but can be remote).

**Comment by yevster** [comment]
[This is a better link](https://career.habr.com/companies/epam-com/vacancies) to all their postings. Some are dated today.

**Comment by masterwto** [comment]
https://b23.tv/o5vHENS

**Comment by vshymanskyy** [comment]
The official statement re Ukraine: https://www.epam.com/about/newsroom/press-releases/2022/epam-provides-update-on-ukraine

However, job listings look suspicious

**Comment by vshymanskyy** [comment]
Moved EPAM to allow list, partially based on an insider info
