### ISSUE TITLE
Remove Telegram

### ISSUE THREAD

**Issue by mtxadmin** [vshymanskyy/StandWithUkraine#36]
Telegram is not a russian project. While its founder and CEO Pavel Durov is russian, he is strongly against russian government and their special services like FSB and Roscomnadzor.

Pavel's previous project, VK social network, was taken from him by force, so he is escaped, started new life and never, never will be in pro-putin mood.

**Comment by mtxadmin** [comment]
Some reading:

https://en.wikipedia.org/wiki/Government_censorship_of_Telegram_Messenger

**Comment by webknjaz** [comment]
Let's not forget that a russian government-baked organizations hold a significant amount of Telegram's bonds: https://www.themoscowtimes.com/2021/03/24/telegram-raises-1bln-with-russian-direct-investment-fund-buying-bonds-a73346.

**Comment by LilithHafner** [comment]
@webknjaz, the source you link indicates that Russia holds $2 million of publicly traded debt issued by a company valued at $30-40 billion. 0.06% debt ownership, which Telegram has no control over, does not make Telegram a Russian-controlled or pro-Russia organization. From what I can tell, Telegram does much more to subvert Russian censorship than to support Russia.

To be effective, boycotts must be accurately targeted, and including Telegram on this list undermines that effort.

Cross-posting from duplicate issue:

> As far as I can tell, Telegram's founder is Russian but is not supporting the war and neither the company nor its product have a net negative impact on Ukraine.
> https://en.wikipedia.org/wiki/Telegram_(software)#Development
> https://en.wikipedia.org/wiki/Pavel_Durov#Career

**Comment by vshymanskyy** [comment]
Agree. Removed
