### ISSUE TITLE
Add MakeYour-Terminal-StayWithUkraine to list !

### ISSUE THREAD

**Issue by alex5250** [vshymanskyy/StandWithUkraine#38]
Hello , I think the one most important software that we are using is terminal , so I decided that it would nice to make project,that will make clear position ! 
here is a link https://github.com/alex5250/MakeYour-Terminal-StayWithUkraine
I think you had no doubts about does this project StayWithUkraine ! 
It will much appreciated if my project will counted ! 
Currently  it supports only Windows PowerShell and ConEmu but the list of supported terminal emulators will increased

**Comment by vshymanskyy** [comment]
Thanks, but the main objective of this repository is to increase awareness.
I'm not sure how adding any slogans to your own console/terminal can help.
