### ISSUE TITLE
Fighting Russian disinformation by distributing `.md` file with popular repos

### ISSUE THREAD

**Issue by Ocramius** [vshymanskyy/StandWithUkraine#4]
### Disinformation ramping up

Hey folks, as you may have already heard, most mainstream media is now banned in Russia, and the disinformation campaign inside their country is ramping up to fight common sense.

Putin is really trying to hide his own crimes in plain sight, by blaming others.

### What I can do

I am maintaining a number of popular open-source packages that are downloaded millions of times worldwide. These are:

 * installed in (hundreds of )thousands production systems
 * hard to take down: critical infrastructure

I want to use them to do some good: spreading a message. Nothing malicious, just distributing information.

### What we need

 * [x] message in Russian, targeted at Russians, aligned with how they communicate (rather than transposed from another language)
 * [x] it needs to be strong, effective, political
 * [x] it must be something that people can copy/paste out of the context of these projects/repositories, and still makes sense to other Russians
 * [x] it must come with a parallel English translation (for the rest of the world to understand what is going on in that file)
 * [x] we should try and be quick - 10 days of war already

### What I can't do

I can't write a political message that comes through to a population whose costume is most unbeknownst to me.
I also don't speak Russian, nor know the Cyrillic alphabet.

### Call for help

I am no diplomat: I'm just trying to do my part, but asking here is possibly the best spot where I can find other people interested in redacting such a message, and then using this repository to explain how to copy it into projects, for distribution.

**Comment by tgalopin** [comment]
I'm asking internally if volunteers from https://isupportukraine.eu are able to do this.

**Comment by vshymanskyy** [comment]
This is an awesome request. Let's make it happen.
How long this message should be (words/characters)?

**Comment by Ocramius** [comment]
In my opinion, it can be multiple pages long, if needed, but it certainly needs a TL;DR at the top, with a strong call to action, or at least encourages reading further.

**Comment by vshymanskyy** [comment]
`TL;DR` might be something like:
```log
As of March 5, 2022, Russian Army casualties exceeded 10’000.
The large-scale Russian invasion of Ukraine killed at least 2000 civilians.
All Russian airlines were banned from international flights. WHY?
```

**Comment by Ocramius** [comment]
Most Russian citizens will likely never go on an international flight anyway (VISA requirements), so perhaps more lever on the fact that most internet access got restricted (almost everyone has internet, I suppose).

**Comment by vshymanskyy** [comment]
Re airlines, this is something acknowledged and widely reported by Russian media right now.

**Comment by p4veI** [comment]
Maybe this could serve as an inspiration for the message as well.. https://1920.in

**Comment by vshymanskyy** [comment]
Check out this: https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/ToRussianPeople.md

**Comment by vshymanskyy** [comment]
@Ocramius WDYT?

**Comment by Ocramius** [comment]
I'm fine with including it - it's time-sensitive, so I'll get a bunch of releases done tonight on my own packages 👍 

Thanks everyone for the speedy reaction: much appreciated.

**Comment by drupol** [comment]
How do you plan to include this message? I'm also interested!

**Comment by Ocramius** [comment]
@drupol just dropping it in, adding it to `README.md`, adding it as a file in the repository, and making it official in release notes too.

**Comment by drupol** [comment]
Ok, will most probably do the same. Thanks for the idea.

**Comment by Ocramius** [comment]
@vshymanskyy I wonder if we can add the quote that "the world won't be destroyed by those who do evil, but by those who watch without doing anything" or such? See this quote at 1:44:48: https://www.youtube.com/watch?v=Gfsiw2pf_Y0&time=1h44m48s

**Comment by vshymanskyy** [comment]
Thank you @Ocramius @drupol 
Of course you can add something like this. But IMHO, this will not strengthen the initial message (in Russian eyes at least)

**Comment by Ocramius** [comment]
Alright 👍

I'll go on with it as-is then 💪

**Comment by terabytesoftw** [comment]
Hi, t's `15 years` of prison, `not 5`.

**Comment by Ocramius** [comment]
"years" would suffice then - they'll keep adjusting that anyway.

**Comment by vshymanskyy** [comment]
agree

**Comment by Ocramius** [comment]
I've done releases and publishing of my most popular packages - that should ensure that the next dependency update will reach downstream consumers at their nest patch upgrade. 

Thanks everyone for the collaboration!

One thing left: endorsing this approach also in the `README.md` on this repository.

**Comment by vshymanskyy** [comment]
will update readme once I get out of the shelter.
Thanks everyone!

**Comment by terabytesoftw** [comment]
Thank you all for this effort, the suffering of the people of Ukraine, and to some extent the Russian people, we all want peace, and respect for ideas, i have Russian comrades who are suffering, and Ukrainian comrades hiding in shelters, I see this and I don't believe it.

**Comment by vshymanskyy** [comment]
Done

**Comment by Ocramius** [comment]
Thanks, closing here, I will try to squeeze some more of my brain cells on further ideas.

**Comment by mnapoli** [comment]
Hey, a few questions I have:

1. If the goal is to inform Russian users/visitors, is there any link we can throw in the text so that these users can have a credible source of information to learn more? Right now the text is short and only links to images that cannot be verified (i.e. all needs to be trusted at face value). I'm trying to put myself in the shoes of someone fed with disinformation: how can we make that more credible and useful?
2. Is there any risk to Russian users who download such text on their machine?

**Comment by Ocramius** [comment]
>  I'm trying to put myself in the shoes of someone fed with disinformation: how can we make that more credible and useful?

I raised this thread specifically because I do not speak nor understand Russian zeitgeist. Multiple Russian-natives suggested that stronger wording, or confrontation-oriented wording would have no effect (or worse effect - see linked `laminas-mvc` issue above)

 > Is there any risk to Russian users who download such text on their machine?

Most likely not: they are dragged in by us maintainers, not by Russian devs upgrading their dependencies.
IANAL, but I think the Russian political landscape cares so little for its citizens that it is getting out of hand regardless: even asking for information may become a criminal offense at this point, so acting quick against propaganda and enforcement is very much necessary.

**Comment by mnapoli** [comment]
> > I'm trying to put myself in the shoes of someone fed with disinformation: how can we make that more credible and useful?
>
> I raised this thread specifically because I do not speak nor understand Russian zeitgeist. Multiple Russian-natives suggested that stronger wording, or confrontation-oriented wording would have no effect (or worse effect - see linked laminas-mvc issue above)

My point is not really about the Russian translation (assuming the english and russian text are nearly identical). It's more than this:

<img width="1060" alt="Screen-000124" src="https://user-images.githubusercontent.com/720328/157228034-17cfd090-1370-4672-86a0-f075746e0d38.png">

doesn't cite any source and doesn't link to any extra information. Photos linked have no way of actually believing if they are actually from this conflict. Heck we've seen so many fake photos/tweets already, even me I have no way of guaranteeing that these are actual photos from the current war 🤷  Combatting disinformation with "here's the actual reality summed up in 1 sentence, and just believe me" sounds light to me, which is why I'm wondering if a link to information sources (in Russian) might help here. (I unfortunately have no idea where to point people to…)

So to be clear, I'm not challenging the whole thing, just wondering how to make it more efficient.

I see that https://github.com/laminas/laminas-mvc/issues/111 took an alternative direction, which is interesting.

**Comment by Ocramius** [comment]
> So to be clear, I'm not challenging the whole thing, just wondering how to make it more efficient.

Totally on board: I shipped early and shipped it everywhere to start spreading earlier rather than later (due to Brandolini's law).

I think you might want to open a new issue about this, perhaps highlighting specific fragments, or proposing alternative wording.

**Comment by jimmywarting** [comment]
pinging some popular developer i know could maybe make an large impact in their own repository / sites

@sindresorhus @ry @warting  @benjamingr @mcollina @voxpelli @ronag @linusu @gr2m @Richienb @TimothyGu @@lucacasonato what do you think about this?

**Comment by glensc** [comment]
https://www.npmjs.com/package/peacenotwar

**Comment by benjamingr** [comment]
@jimmywarting Node.js is off the table since adding a banner is dangerous for our Russian project members because of the regime there. We _tried_ and eventually removed it.

For anything I personally own I would strongly prefer _not_ to add a banner (since that feels very performative) and instead do something that actually supports Ukranians. There have been many initiatives in Israel (where I live) to help Ukranian developers (lots of companies here have offices in Kiev) - mostly with legal stuff (helping with papers, calling delegates etc).

I am open to ideas or if someone wants to throw together a fundraiser-conference I'm happy to contribute a talk to that.

**Comment by benjamingr** [comment]
Oh, I see the ask in this particular issue is:

> distributing .md file with popular repos

Sorry. I am strictly against that for any of my stuff as well as for Node.js. When users install software their expectation is for that software to do what is promised and nothing else. There is implicit trust between the maintainer and the user regarding the software not doing unexpected things. Adding any political messages to software on users' computers seems trust-breeching to me and I care about the people using my code - so I am strictly against that. It is also feels like a very performative form of allyship.

Note I held this opinion when I was in a bomb-shelter with my infant son while rockets were fired on my home. I still hold this opinion. So basically my personal political opinion and willingness to take action about it does not mean I am willing to compromise any packages I own.

Software is political, I acknowledge I work on open source and answer stuff on Q&A sites for ideological political reasons and I believe it helps narrow the knowledge gap and improve social mobility. I honestly believe it enables people to build things and improve their lives. I have a lot of respect for power and trust I have from the community as a maintainer and I won't do anything that can undermine that.

The situation in the Ukraine is truly awful and I pray for the safety of the Ukranian people. I promise to continue to take action as I am able.
