### ISSUE TITLE
Do you think you can sanction all countries that import Russian energy?

### ISSUE THREAD

**Issue by LukaDong77** [vshymanskyy/StandWithUkraine#41]
Do you think you can sanction all countries that import Russian energy (including the motherland of those who support you now)? Do you think the lives of Ukrainians are more noble than those of Iraqis? Have you ever sanctioned the United States? I'm just looking at it from a spectator's point of view. I am not familiar with Ukraine and Iraq. You are a witness, and Iraqis are also witnesses. From a credibility point of view, there is no difference between you. If no one dares to sanction the United States, don't expect too much from sanctions against Russia. Americans say Iraq has weapons of mass destruction. Russia also says Ukraine has extremist organizations, and an American biological laboratory has been found in Ukraine. In the final analysis, the Ukrainian issue is the struggle between the United States and Russia. The United States is just borrowing Ukraine to weaken Russia. Alas, Ukraine is just a chess piece. Avoid being someone else's pawn.

**Comment by delucis** [comment]
Using one unjustified invasion to dismiss criticism of another is illogical.

Russia has lied about extremist organisations in Ukraine and spread false rumours about laboratories there, but these claims are not true. Please do not help to spread them.

Some sources debunking your false claims:

https://www.theguardian.com/world/2022/mar/13/is-there-any-justification-for-putins-war

https://www.snopes.com/news/2022/02/24/us-biolabs-ukraine-russia/

**Comment by sergiomarotco** [comment]
Supscribe to russian project: https://github.com/sergiomarotco/Network-segmentation-cheat-sheet
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=sergiomarotco&show_icons=true&theme=radical)
