### ISSUE TITLE
Troubles with docs/Boycott.md

### ISSUE THREAD

**Issue by artginzburg** [vshymanskyy/StandWithUkraine#50]
Is there any reason for Google not being in the [Boycott list](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/Boycott.md), and also not being in the [allow list](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/Boycott.md#allow-list)? It seems like it's been forgotten at all.

I also don't see how are Telegram and Nginx considered Russian products (and much less businesses), apart from being vaguely originated from Russia (as well as Google).

> There are several companies on the boycott list that I'm not familiar with, so I have for sure missed some of them.

Also, there are indeed some missing companies that are both definitely Russian and a business (e.g. Tinkoff, Alfa and other banks).

<br/>

### What's written next are my pure opinionated thoughts with almost no intended facts underneath.

As a developer in open-source community, I believe nothing should be deleted or suspended forever. And what I want much less is digging through all of my dependencies to see if they have any Russian origins. Even if I wanted to do this, I would probably also write a script that automatically turns every package and repository affected by the boycott back to stable functioning after Russian leadership is suspended.

I don't consider Google, Telegram, and Nginx Russian products. I would as well be interested to know how "Russian" should something be to be included in the boycott. Does something that was not Russian but is now in Russia become boycotted (if a coin from another country is taken to Russia), and vice-versa (if a Russian-originated open-source developer takes a flight to Florida and ditches his Russian passport).

I think concepts and recipes should not, for sure, be included in the boycott, like dumplings or beef stroganoff. This includes all of the Russian-originated open-source software (because source code is a recipe of some kind).

> Unrelated to the issue: we have a saying here, "Moscow is not Russia" (can be googled easily). After 24 Feb, my brain just asked "Well, if it's not Russia, then what it actually is?". The answer made many people laugh and since lives in the location field of my GitHub profile: "Moscow, Ukraine".

**Comment by vshymanskyy** [comment]
I don't want to spend time on philosophy here. 
If you think Google needs to be on any of the lists, explain why and maybe we can include it.
