### ISSUE TITLE
Did you take into account the actions of the Ukrainian military while war in Donbas before suggesting to help them?

### ISSUE THREAD

**Issue by skirpichev** [vshymanskyy/StandWithUkraine#52]
Lets make it clear.  I'm against this war and I would like, at least, to spread your message (e.g. via my GH account and friends).  Even if it will cost me a jail.

But more than 172 children had been injured or killed while war in Donbas,  among other civilian loses.  See e.g. [this](https://www.unicef.org/press-releases/430000-children-continue-bear-brunt-eastern-ukraine-conflict) or [this memorial](https://en.wikipedia.org/wiki/Alley_of_Angels), 66 names listed.  I'm afraid, but most of this - due to shells and mines of the Ukrainian military.  You suggest to support that too.  How this is different from the support for actions of Putin's forces?

**Comment by webknjaz** [comment]
That is included automatically. Especially taking into account that those bombings are the result of russian nazi strikes too (pretending to fired from Ukraine for propaganda purposes). Everybody here knows that Ukraine doesn't bomb itself.

**Comment by skirpichev** [comment]
> That is included automatically.

Lets hope, I misread you.  Do you support killing children only by the Ukrainian military?

> Especially taking into account that those bombings are the result of russian nazi too

Sure, but hardy all of them, even most, if the Ukrainian army ever shots over the territory, which is under the control of separatists (lets call them russian nazi, ok) forces (which in a decent part are ukrainian people too).

> Everybody here knows that Ukraine doesn't bomb itself.

How everybody have checked that?

**Comment by vshymanskyy** [comment]
> Lets hope, I misread you. Do you support killing children only by the Ukrainian military?

First of all, Ukrainian Forces never targeted children or residential buildings. Even if there were casualties, it was not on purpose.

On the other side, Russian-backed separatists and Russian Forces are proven to use civilians as a shield, as well as targeting civilians and children (and then shifting responsibility to Ukrainian Forces).

I see no reason to duscus it further. Do you labor, try to educate yourself. Look for truth.

**Comment by skirpichev** [comment]
> First of all, Ukrainian Forces never targeted children or residential buildings.

They certainly use non-guided munition.

> Even if there were casualties, it was not on purpose.

Same claims Putin's Forces.  And I see no reasons to disbelieve in this (not because Putin is a great humanist).

> On the other side, Russia-backed separatists and Russian Forces are proven to use civilians as a shield.

Same claims from the other side.  And there are proofs, e.g. videos of artillery positions of the Ukrainian forces in the city.

> I see no reason to duscus it further.

You certainly do a lot to get more support among people of Russia.

Could you kindly explain in #24 what exactly do you mean by "We really want to kill Russia"?

Thank for your time.

**Comment by vshymanskyy** [comment]
This discussion is a dead-en
*"Why does Russia want to kill Ukraine (and ukrainians)?**
We can keep asking questions like that.

**Comment by skirpichev** [comment]
That wasn't my question.  But I'll stop first.  Thank you for your time.
