### ISSUE TITLE
Congratulation with success

### ISSUE THREAD

**Issue by tarkhil** [vshymanskyy/StandWithUkraine#56]
Yesterday, Ukraine launched Tochka-U, hitting Donetsk and killing over 20 civilians.

That's a huge success for Ukraine.

What's more, photos of dead civilians in Donetsk were used as a photo of Kiev.

![image](https://user-images.githubusercontent.com/509303/158433748-dfda6ac7-cf92-402a-9dc7-5eb08feb3c5b.png)

**Comment by aiperon** [comment]
There is no place for this propaganda-driven issue here. 
@[vshymanskyy](https://github.com/vshymanskyy) I suggest to just close this issue without any discussion

**Comment by tarkhil** [comment]
> There is no place for this propaganda-driven issue here. @[vshymanskyy](https://github.com/vshymanskyy) I suggest to just close this issue without any discussion

Where did you get any propaganda? Donetsk was hit yesterday, and "Azov" is happy with Nazi flag.

**Comment by aiperon** [comment]
You couldn't confirm that. Is it Azov and not the people with captured flags ("постанова")? Is this photo is taken in Donetsk? And what the heck this issue help this project?
