### ISSUE TITLE
Add Banner Explicitly denying use of software for User's repos

### ISSUE THREAD

**Issue by cmcintosh** [vshymanskyy/StandWithUkraine#6]
It would be good to get a yellow/blue banner similar to the one on the repo that explicitly denies all use of any repo under my user account to any organizations / government or private located in Russia and allied nation-states currently engaged in aggression against ukraine.

**Comment by vshymanskyy** [comment]
will do. easy.

**Comment by vshymanskyy** [comment]
Ok. Thinking about this for a while, looks like you'll have to modify your license instead.
