### ISSUE TITLE
Не понимаю ваши двойные стандарты

### ISSUE THREAD

**Issue by Maxwellwr** [vshymanskyy/StandWithUkraine#62]
Я не могу понять ваши двойные стандарты. Почему вы все молчали, пока 8 лет ВСУ расстреливало Донецк и Луганск? Почему никто не вышел на улицы, когда Украина просто перекрыла Северо-Крымский канал с целью оставить жителей Крыма без воды? это все вы считали прям в порядке вещей. Ну а что такого. Почему не было никакой инициативы во время конфликта в Сирии, Грузии, Абхазии, Чечне, Югославии? Все это для вас было нормой. Точнее вам было насрать на это. Так почему вы решили, что всем остальным не точно так-же насрать на ваши проблемы?

**Comment by Maxwellwr** [comment]
И да, этот посто можно удалять. Ведь существует только 2 мнения: ваше и не верное.

**Comment by Maxwellwr** [comment]
Да в конце концов почему в 2010 когда я просто порездом было во Львове я уехал оттуда из больнички со сломаной ногой? Просто потому, что говорил на русском. Серьезно? Это нормально?

**Comment by 55pingvin** [comment]
> Да в конце концов почему в 2010 когда я просто порездом было во Львове я уехал оттуда из больнички со сломаной ногой? Просто потому, что говорил на русском. Серьезно? Это нормально?

конечно. в цивилизованных странах так принято.

**Comment by 55pingvin** [comment]
не. это все ужасно и плохо. гибнут люди. но вот когда на главной площади страны скачет толпа и кричит "маскаляку на гиляку"... это может еще не выглядит как угроза, но людей становилось все больше и больше.
а если у нас так выйти на главную площадь и начать кричат что то подобное? 
я был в Киеве в 2010 году и вот честно сказать это стрем, когда люди отворачиваются от тебя когда ты что то спрашиваешь на русском. стыд и позор.

**Comment by vshymanskyy** [comment]
О боже, какие все ущемлённые. Может вам (и вашым детям) вьебать ФАБ-500?
Ведь ето и есть справедливость и освобождение "по-русски".

**Comment by vshymanskyy** [comment]
И еще, перестаньте себя вести как свиньи в других странах, возможно вас гдето и полюбят.

**Comment by 55pingvin** [comment]
@vshymanskyy а вы тоже скакали на майдане?
жили в Донецке, где почти каждый день прилетал снаряд?
да я далеко от этих мест, но есть знакомые, которые так жили и до них никому не было дела.

**Comment by 55pingvin** [comment]
конфликтов с русскими за границе куда меньше, простите, конечно, но можно посмотреть сводки из прессы или тик-токи и ютубы всякие. 
по первой ссылке
https://esp.md/ru/podrobnosti/2022/03/05/bezhency-raskrashivayut-tanki-pamyatniki-v-cveta-ukrainskogo-flaga-i-drugie

**Comment by vshymanskyy** [comment]
Я конечно, не буду вас преубеждать. Читайте здесь https://github.com/vshymanskyy/StandWithUkraine/issues/61#issuecomment-1070594299
И здесь https://github.com/vshymanskyy/StandWithUkraine/issues/2, и еще другие issues.

**Comment by vshymanskyy** [comment]
Вот, арнольд тоже "продался"
https://twitter.com/Schwarzenegger/status/1504426844199669762
