### ISSUE TITLE
There's no point in what you're doing. You're really hypocritical and double-standard. If you really support Ukraine, you should go to war.

### ISSUE THREAD

**Issue by Generalize** [vshymanskyy/StandWithUkraine#72]

**Comment by FoggyFinder** [comment]
> There's no point in what you're doing.

Because? No arguments. As expected.

> You're really hypocritical and double-standard.

Where?

**Comment by Froggo8311** [comment]
> If you really support Ukraine, you should go to war. 

War doesn't solve everything. Or most things. Come to think of it, I can't think of any time where war is the only option to create a desired outcome.
