### ISSUE TITLE
ManyChat False Positive

### ISSUE THREAD

**Issue by mask-is-he** [vshymanskyy/StandWithUkraine#73]
ALLOW LIST
ManyChat

Statements:
- [ManyChat’s Update on Ukraine](https://manychat.com/blog/manychats-update-on-ukraine/) (16th March 2022)

Actions:
- Suspend all operations and new sales in Russia
- Waived fees for all users from Ukraine till the end of 2022
- Donate all revenues from Instagram Summit ticket sales to charity organizations to help relieve the humanitarian crisis in Ukraine

**Comment by vshymanskyy** [comment]
Done
