### ISSUE TITLE
Electrics Eagles project is StandWithUkraine

### ISSUE THREAD

**Issue by alex5250** [vshymanskyy/StandWithUkraine#77]
Here are links to repos, but all of them are related to one project, Electrics Eagles! And we StandWithUkraine
https://github.com/Electrics-Eagles/PiElectricsEagles-dev
https://github.com/Electrics-Eagles/PiElectricsEaglesOS

**Comment by alex5250** [comment]
https://www.eeagles.net/pielectricseagles/ also on website there are note about the war!

**Comment by vshymanskyy** [comment]
Thank you
