### ISSUE TITLE
"death toll is still counting" should be "still climbing"

### ISSUE THREAD

**Issue by nedbat** [vshymanskyy/StandWithUkraine#84]
The banners are great, but "still counting" is odd English.  The usual idiom is "still climbing", which you are already using in one place.

I'd offer a pull request, but I didn't want to break the .svg in a way I didn't understand.

**Comment by vshymanskyy** [comment]
Thanks, will it in all banners asap

**Comment by webknjaz** [comment]
@nedbat thanks a lot for pointing this out, Ned!

By the way, how did you come across our little project? Did you consider adding a banner to coveragepy?

P.S. Updating text in SVG would only be noticeable if the line length is increased significantly. Pull Requests allow previewing these images right in the GH UI. JFYI.

**Comment by vshymanskyy** [comment]
I'm working on it, will be ready in minutes!

**Comment by nedbat** [comment]
I've added it to [my profile](https://github.com/nedbat) and [coverage.py](https://github.com/nedbat/coveragepy).

**Comment by vshymanskyy** [comment]
Thank you

**Comment by webknjaz** [comment]
Thank you for your support 🙏
