### ISSUE TITLE
Author contribution for peace

### ISSUE THREAD

**Issue by a-astapov** [vshymanskyy/StandWithUkraine#86]
The author shifts the responsibility for the military operation to the citizens of Russia.
It would be strange if the author did not write about his contribution for peace.
Let the author write what he had been done in 2014-2022 in order to prevent this conflict.
Did the author come out with posters "No war in Donbass"?

**Comment by reignmaker** [comment]
For everyone interested in where and why did this all started, please watch this video from a American/French journalist Vladimir Pozner. He gave a speech in the Yale University in 2018 (!). https://www.youtube.com/watch?v=8X7Ng75e5gQ

**Comment by reignmaker** [comment]
One more video to watch from 2015 of John J. Mearsheimer, the R. Wendell Harrison Distinguished Service Professor in Political Science  https://www.youtube.com/watch?v=JrMiSQAGOS4

**Comment by vshymanskyy** [comment]
Citizens of Russia are FULLY responsible. Citizens of Russia ARE sitting in tanks and warships.
They are pushing buttons to launch rockets.
They ARE purposely aiming assault rifles at civilians, children, and shooting.
