### ISSUE TITLE
Remove Telegram from boycott list

### ISSUE THREAD

**Issue by LilithHafner** [vshymanskyy/StandWithUkraine#87]
As far as I can tell, Telegram's founder is Russian but is not supporting the war and neither the company nor its product have a net negative impact on Ukraine.
https://en.wikipedia.org/wiki/Telegram_(software)#Development
https://en.wikipedia.org/wiki/Pavel_Durov#Career

**Comment by vshymanskyy** [comment]
https://github.com/vshymanskyy/StandWithUkraine/issues?q=is%3Aissue+Telegram+is%3Aclosed

**Comment by LilithHafner** [comment]
moved to https://github.com/vshymanskyy/StandWithUkraine/issues/36
