### ISSUE TITLE
Issue with red cross

### ISSUE THREAD

**Issue by sdwvit** [vshymanskyy/StandWithUkraine#92]
There is a plenty info on subject on the internet. Do you think we can/should remove red cross from the list?

**Comment by vshymanskyy** [comment]
Ukrainian Red Cross is included in the list.
And there's an explicit note about Red Cross International. Do you think more should be done?

**Comment by sdwvit** [comment]
> ⚠ DO NOT donate to Red Cross International, donate to [Ukrainian Red Cross](https://redcross.org.ua/en/donate) instead.

im blind. closed
