### ISSUE TITLE
Luxoft is staying in Russia

### ISSUE THREAD

**Issue by mismatch** [vshymanskyy/StandWithUkraine#94]
Proof link https://career.luxoft.com/job-opportunities/?keyword=&country%5B%5D=russian%2Bfederation&set_filter=Y

**Comment by vshymanskyy** [comment]
There is not enough evidence those are new job opportunities, maybe they just didn't clean them up.

**Comment by mismatch** [comment]
What about https://hh.ru/employer/1304 ?

**Comment by mismatch** [comment]
Additional info
https://dou.ua/lenta/articles/luxoft-is-working-in-russia/

**Comment by houp** [comment]
It's very hard to check this... as they have so many "fully remote" positions open I guess it's very easy for them to "convert" all the Russian employees to "remote workers" associated with one of the existing offices in Poland or other country nearby.

**Comment by luke-hill** [comment]
The dropdown list now features no Russian option and I couldn't spot any russian jobs. Not sure if it's just me

**Comment by fabswt** [comment]
I suppose you folks banned Americans from getting work during the war in Iraq?

People working with tech are supposed to be rational. Yet so many people remain blind to double standards.

War is obviously bad. But lack of rationality doesn't help. Peace requires reason, not vindicative hatred.
