### ISSUE TITLE
The existence of this repository is ridiculous.

### ISSUE THREAD

**Issue by bluemiaomiao** [vshymanskyy/StandWithUkraine#97]
Ukraine is just a pawn between NATO and the United States. Do you face up to the cause of the war? When western countries bombed other places in the early days, wouldn't our people bleed? Opposing the war is not necessarily against Russia. The origin of this war is some western countries such as the United States.

**Comment by bluemiaomiao** [comment]
During the Russian-Ukrainian War, the United States and NATO sent guns and ammunition to Ukraine, and made a big profit by it. China sent protective materials such as food. Although Ukrainian civilians have suffered heavy casualties and deserve sympathy, isn't it that Russia's interests have been invaded and occupied? The president of Ukraine can only be blamed for being a comedian, and it is foolish enough for Ukraine to elect an actor with no political mind as its president. Everything happens for a reason.

**Comment by jdreesen** [comment]
In Germany we say: "Wenn man keine Ahnung hat, einfach mal die Fresse halten." ;)

**Comment by bluemiaomiao** [comment]
> In Germany we say: "Wenn man keine Ahnung hat, einfach mal die Fresse halten." ;)

Face up to history.

**Comment by bluemiaomiao** [comment]
It is only a matter of time before NATO and the United States become the former Soviet Union. Let's break up these two political gangs as soon as possible.

**Comment by bluemiaomiao** [comment]
THE RESPONSIBILITY LIES ENTIRELY WITH THE US.

**Comment by bluemiaomiao** [comment]
Ironically, this [ISSUE](https://github.com/vshymanskyy/StandWithUkraine/issues/24#issuecomment-1065040284) was forcibly locked by the reply, so we consider this repository as a way to vent our personal anger? So, is it efficient for you to build a repository on GitHub?

**Comment by bluemiaomiao** [comment]
Getting rid of the Ukrainian government, electing outstanding people with political minds as presidents, and maintaining neutrality and peaceful development are the way out for the Ukrainian people.

**Comment by vshymanskyy** [comment]
[![RussianWarship](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/README.md)

**Comment by vshymanskyy** [comment]
The existance of "the Russia" is ridiculous, if you will.

**Comment by vshymanskyy** [comment]
Освободители хреновьі. Пришли, разбомбили мой дом и ограбили, изнасиловали соседок и уехали назад на Беларусь хвастаться награбленньім. 
И еще буду видеть хамскую рускую харю, рассказьівающую кто виноват иикак ето воспринимать. Горите в аду, ублюдки

**Comment by vshymanskyy** [comment]
https://twitter.com/denysdovhan/status/1510351014842535939?t=1a_mFxlte7j-z9HmQ_a8Tw&s=19

**Comment by vshymanskyy** [comment]
so... what?

**Comment by bluemiaomiao** [comment]
Recent news: Ukrainian troops fired missiles to bomb Wudong Railway Station and used civilians as human shields to protect Ukrainian positions. 

Facts have proved that it is always the incompetent Ukrainian government that hurts Ukrainian civilians.

Ukrainian civilians are innocent. The United States and NATO are the initiators of this war.

**Comment by bluemiaomiao** [comment]
And the United States and NATO use Ukraine as a pawn to restrict Russia, just because the Ukrainian president has no political mind. Isn't it good to be a neutral country? At present, the Ukrainian government is the biggest joke.
